MANIFEST: Makefile: Makefile.global.in: configure: configure.in: 	- incorporate patch from Clayton and Richard 	- delete uninportant stuff(obsolete, syslog etc.) 	- drop uniover stuff 	- drop expireindex and overchan stuff 	- drop traditional stuff

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -285,9 +285,11 @@ then
 	LFS_CFLAGS=`$GETCONF LFS_CFLAGS`
 	LFS_LDFLAGS=`$GETCONF LFS_LDFLAGS`
 	LFS_LIBS=`$GETCONF LFS_LIBS`
+	AC_CHECK_FUNCS(ftello fseeko)
+
 	AC_SUBST(LFS_CFLAGS)
 	AC_SUBST(LFS_LDFLAGS)
-	AC_SUBST(LFS_LFS_LIBS)
+	AC_SUBST(LFS_LIBS)
 fi
 
 AC_PATH_PROG(COMPRESS,compress,no-compress-found-during-configure)
@@ -367,6 +369,20 @@ AC_CHECK_LIB(44bsd,  inet_addr)
 AC_CHECK_LIB(bind,  __inet_addr)
 AC_CHECK_LIB(resolv, gethostbyname, ac_need_libresolv=1, ac_try_bind=1)
 AC_CHECK_LIB(resolv, inet_aton, ac_need_libresolv=1, ac_try_bind=1)
+AC_CHECK_LIB(thread, pthread_create, ac_have_thread=1)
+if test x$ac_have_thread = x1; then
+	THREADFLAGS="-D_REENTRANT -DPOSIX_PTHREAD_SEMANTICS -D_THREAD_SAFE"
+	THREADLIB=-lthread
+else
+	AC_CHECK_LIB(pthread, pthread_create, ac_have_pthread=1)
+	if test x$ac_have_pthread = xyes; then
+		THREADFLAGS="-D_REENTRANT -DPOSIX_PTHREAD_SEMANTICS -D_THREAD_SAFE"
+		THREADLIB=-lpthread
+	fi
+fi
+AC_SUBST(THREADLIB)
+AC_SUBST(THREADFLAGS)
+
 if test x$ac_need_libresolv = x1
 then
 LIBS="$LIBS -lresolv"
@@ -456,7 +472,7 @@ AC_HEADER_TIME
 AC_HEADER_SYS_WAIT
 AC_CHECK_HEADERS(fcntl.h limits.h memory.h sgtty.h stdarg.h)
 AC_CHECK_HEADERS(stdlib.h string.h sys/file.h sys/filio.h sys/ioctl.h)
-AC_CHECK_HEADERS(sys/select.h sys/signal.h sys/time.h syslog.h unistd.h)
+AC_CHECK_HEADERS(sys/select.h sys/signal.h sys/time.h unistd.h)
 AC_CHECK_HEADERS(varargs.h dirent.h wait.h getopt.h sys/sysinfo.h)
 AC_CHECK_HEADERS(ndbm.h db1/ndbm.h)
 
@@ -531,7 +547,7 @@ AC_CHECK_FUNCS(gettimeofday memchr memcmp memcpy memmove memset)
 AC_CHECK_FUNCS(mkdir mkfifo mktemp select setbuffer setproctitle)
 AC_CHECK_FUNCS(setsid socket strcasecmp strchr strcspn strerror)
 AC_CHECK_FUNCS(strrchr strspn strstr symlink sysconf syslog ulimit)
-AC_CHECK_FUNCS(waitpid socketpair getpagesize getspnam)
+AC_CHECK_FUNCS(waitpid socketpair getpagesize getspnam pwrite pread)
 AC_CHECK_FUNCS(statvfs, [AC_DEFINE(HAVE_STATVFS)], [AC_CHECK_FUNCS(statfs) AC_CHECK_HEADERS(sys/vfs.h, AC_DEFINE(HAVE_SYS_VFS_H)) AC_CHECK_HEADERS(sys/param.h, AC_DEFINE(HAVE_SYS_PARAM_H)) AC_CHECK_HEADERS(sys/mount.h, AC_DEFINE(HAVE_SYS_MOUNT_H))])
 
 if test $ac_cv_func_getrlimit = yes; then
@@ -1029,9 +1045,8 @@ then
 fi
 if test ${ac_cv_func_syslog} = "no"
 then
-	MISSING_MAN="${MISSING_MAN}syslog.3 "
-	MISSING_SRC="${MISSING_SRC}syslog.c "
-	MISSING_OBJ="${MISSING_OBJ}syslog.o "
+	echo "INN required support for syslog(3)"
+	exit 1;
 fi
 if test ${ac_cv_func_strerror} = "no"
 then
@@ -1163,7 +1178,6 @@ AC_OUTPUT(
 	samples/version.pl
 	samples/writelog
 	storage/buildconfig 
-	syslog/syslog.conf
 	,
 	chmod +x storage/buildconfig
 )
