This should result in samples not requiring subst
In site, there is a 'subst.pl' generated by configure that is used in the
place of subst when you make

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1397,10 +1397,47 @@ then
 fi
 
 
+# Extract the first word of "sh", so it can be a program name with args.
+set dummy sh; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:1404: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path__PATH_SH'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$_PATH_SH" in
+  /*)
+  ac_cv_path__PATH_SH="$_PATH_SH" # Let the user override the test with a path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
+  for ac_dir in $PATH; do
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path__PATH_SH="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  ;;
+esac
+fi
+_PATH_SH="$ac_cv_path__PATH_SH"
+if test -n "$_PATH_SH"; then
+  echo "$ac_t""$_PATH_SH" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+if test "x${_PATH_SH}" = "x"
+then
+{ echo "configure: error: sh is a required program not found in path" 1>&2; exit 1; }
+fi
+
+
 # Extract the first word of "compress", so it can be a program name with args.
 set dummy compress; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1404: checking for $ac_word" >&5
+echo "configure:1441: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_ac_cv_subst_path_compress'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1432,7 +1469,7 @@ fi
 # Extract the first word of "gzip", so it can be a program name with args.
 set dummy gzip; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1436: checking for $ac_word" >&5
+echo "configure:1473: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_ac_cv_subst_path_gzip'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1464,7 +1501,7 @@ fi
 # Extract the first word of "pgp", so it can be a program name with args.
 set dummy pgp; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1468: checking for $ac_word" >&5
+echo "configure:1505: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_ac_cv_subst_path_pgp'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1491,43 +1528,6 @@ if test -n "$ac_cv_subst_path_pgp"; then
   echo "$ac_t""$ac_cv_subst_path_pgp" 1>&6
 else
   echo "$ac_t""no" 1>&6
-fi
-
-
-# Extract the first word of "sh", so it can be a program name with args.
-set dummy sh; ac_word=$2
-echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1501: checking for $ac_word" >&5
-if eval "test \"`echo '$''{'ac_cv_path_ac_cv_subst_path_sh'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  case "$ac_cv_subst_path_sh" in
-  /*)
-  ac_cv_path_ac_cv_subst_path_sh="$ac_cv_subst_path_sh" # Let the user override the test with a path.
-  ;;
-  *)
-  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS="${IFS}:"
-  for ac_dir in $PATH; do
-    test -z "$ac_dir" && ac_dir=.
-    if test -f $ac_dir/$ac_word; then
-      ac_cv_path_ac_cv_subst_path_sh="$ac_dir/$ac_word"
-      break
-    fi
-  done
-  IFS="$ac_save_ifs"
-  ;;
-esac
-fi
-ac_cv_subst_path_sh="$ac_cv_path_ac_cv_subst_path_sh"
-if test -n "$ac_cv_subst_path_sh"; then
-  echo "$ac_t""$ac_cv_subst_path_sh" 1>&6
-else
-  echo "$ac_t""no" 1>&6
-fi
-
-if test "x${ac_cv_subst_path_sh}" = "x"
-then
-{ echo "configure: error: sh is a required program not found in path" 1>&2; exit 1; }
 fi
 
 
@@ -5277,10 +5277,10 @@ s%@_PATH_SED@%$_PATH_SED%g
 s%@_PATH_DF@%$_PATH_DF%g
 s%@_PATH_EGREP@%$_PATH_EGREP%g
 s%@_PATH_SORT@%$_PATH_SORT%g
+s%@_PATH_SH@%$_PATH_SH%g
 s%@ac_cv_subst_path_compress@%$ac_cv_subst_path_compress%g
 s%@ac_cv_subst_path_gzip@%$ac_cv_subst_path_gzip%g
 s%@ac_cv_subst_path_pgp@%$ac_cv_subst_path_pgp%g
-s%@ac_cv_subst_path_sh@%$ac_cv_subst_path_sh%g
 s%@ac_cv_subst_path_sendmail@%$ac_cv_subst_path_sendmail%g
 s%@PERL_LIB@%$PERL_LIB%g
 s%@PERL_INC@%$PERL_INC%g
