Reformat shell code with shfmt
Manually remove remaining tabulations in comments.

diff --git a/backends/actsyncd.in b/backends/actsyncd.in
--- a/backends/actsyncd.in
+++ b/backends/actsyncd.in
@@ -4,18 +4,18 @@
 # actsyncd - actsync daemon
 #
 # usage:
-#	actsyncd config_file [debug_level [debug_outfmt]]
+#       actsyncd config_file [debug_level [debug_outfmt]]
 #
-#	config_file	name of file used to determine how to run actsync
-#	debug_level	force no action and use -v debug_level
-#	debug_outfmt	change -o a1 output to -o debug_outfmt for debug
+#       config_file     name of file used to determine how to run actsync
+#       debug_level     force no action and use -v debug_level
+#       debug_outfmt    change -o a1 output to -o debug_outfmt for debug
 
-# By: Landon Curt Noll  	chongo@toad.com		(chongo was here /\../\)
+# By: Landon Curt Noll  chongo@toad.com  (chongo was here /\../\)
 #
 # Copyright (c) Landon Curt Noll, 1993.
 # All rights reserved.
 #
-# Permission to use and modify is hereby granted so long as this 
+# Permission to use and modify is hereby granted so long as this
 # notice remains.  Use at your own risk.  No warranty is implied.
 
 # preset vars
@@ -32,15 +32,29 @@ NOSYNC=127
 #
 if [ $# -gt 1 ]; then
     case $1 in
-    -x|-r) shift ;;     # no longer relevant
+    -x | -r) shift ;; # no longer relevant
     esac
 fi
 case $# in
-    1) cfg="$1"; DEBUG=; DEBUG_FMT=; ;;
-    2) cfg="$1"; DEBUG="$2"; DEBUG_FMT=; ;;
-    3) cfg="$1"; DEBUG="$2"; DEBUG_FMT="$3"; ;;
-    *) echo "usage: $0 config_file [debug_level [debug_outfmt]]" 1>&2;
-       exit 1 ;;
+1)
+    cfg="$1"
+    DEBUG=
+    DEBUG_FMT=
+    ;;
+2)
+    cfg="$1"
+    DEBUG="$2"
+    DEBUG_FMT=
+    ;;
+3)
+    cfg="$1"
+    DEBUG="$2"
+    DEBUG_FMT="$3"
+    ;;
+*)
+    echo "usage: $0 config_file [debug_level [debug_outfmt]]" 1>&2
+    exit 1
+    ;;
 esac
 if [ ! -s "$cfg" ]; then
     echo "$0: config_file not found or empty: $ign" 1>&2
@@ -49,23 +63,23 @@ fi
 
 # parse config_file
 #
-host="`sed -n -e 's/^host=[ 	]*//p' $cfg | tail -n 1`"
+host="$(sed -n -e 's/^host=[ 	]*//p' $cfg | tail -n 1)"
 if [ -z "$host" ]; then
     echo "$0: no host specified in $cfg" 1>&2
     exit 3
 fi
-flags="`sed -n -e 's/^flags=[ 	]*//p' $cfg | tail -n 1`"
+flags="$(sed -n -e 's/^flags=[ 	]*//p' $cfg | tail -n 1)"
 if [ -z "$flags" ]; then
     echo "$0: no flags specified in $cfg" 1>&2
     exit 4
 fi
-ign="`sed -n -e 's/^ignore_file=[ 	]*//p' $cfg | tail -n 1`"
+ign="$(sed -n -e 's/^ignore_file=[ 	]*//p' $cfg | tail -n 1)"
 if [ -z "$ign" ]; then
     echo "$0: no ignore file specified in $cfg" 1>&2
     exit 5
 fi
-ftp="`sed   -n -e 's/^ftppath=[ 	]*//p' $cfg | tail -n 1`"
-spool="`sed -n -e 's/^spool=[ 	]*//p' $cfg | tail -n 1`"
+ftp="$(sed -n -e 's/^ftppath=[ 	]*//p' $cfg | tail -n 1)"
+spool="$(sed -n -e 's/^spool=[ 	]*//p' $cfg | tail -n 1)"
 if [ -z "$spool" ]; then
     spool=$SPOOL
     #echo "$0: no spool directory specified in $cfg" 1>&2
@@ -92,7 +106,7 @@ else
 
     if [ ! -z "$ftp" ]; then
         echo "$0: cannot use DEBUG mode with ftp (yet)" >&2
-        exit 88;
+        exit 88
     fi
 
     # force -v level as needed
@@ -100,11 +114,13 @@ else
 
     # force -o level but reject -o x modes
     if [ ! -z "$DEBUG_FMT" ]; then
-	case "$DEBUG_FMT" in
-	x*) echo "$0: do not use any of the -o x debug_outfmt modes!" 1>&2;
-	    exit 8 ;;
-	*) flags="$flags -o $DEBUG_FMT" ;;
-	esac
+        case "$DEBUG_FMT" in
+        x*)
+            echo "$0: do not use any of the -o x debug_outfmt modes!" 1>&2
+            exit 8
+            ;;
+        *) flags="$flags -o $DEBUG_FMT" ;;
+        esac
     fi
 
     # execute actsync directly
@@ -118,13 +134,13 @@ fi
 # Lock out others
 #
 shlock -p $$ -f "${LOCK}" || {
-    echo "$0: Locked by `cat \"${LOCK}\"`" 1>&2
+    echo "$0: Locked by $(cat \"${LOCK}\")" 1>&2
     exit 9
 }
 
 # setup
 #
-origdir=`pwd`
+origdir=$(pwd)
 workdir="${TMPDIR}/actsyncd"
 ctlinndcmds="cc_commands"
 out="sync.msg"
@@ -141,77 +157,83 @@ rm -f "$out"
 touch "$out"
 chmod 0644 "$out"
 
-# try to sync 
-# 
+# try to sync
+#
 # Try to sync off of the host.  If unable to connect/sync then retry
 # up to 9 more times waiting 6 minutes between each try.
 #
-echo "=-= `date` for $host" >>$out 2>&1
+echo "=-= $(date) for $host" >>$out 2>&1
 for loop in 1 2 3 4 5 6 7 8 9 10; do
 
     # get the active file to compare against
     status=0
     case $host in
-    /*) cp $host          active; status=$? ;;
-    .*) cp $origdir/$host active; status=$? ;;
-     *)
+    /*)
+        cp $host active
+        status=$?
+        ;;
+    .*)
+        cp $origdir/$host active
+        status=$?
+        ;;
+    *)
         if [ -z "$ftp" ]; then
-           port=`expr "$host" : '.*:\(.*\)'`
-           if [ -n "$port" ]; then
-             port="-p $port"
-             host=`expr "$host" : '\(.*\):.*'`
-           fi
-           echo "getlist -h $host $port" >>$out
-           if getlist -h $host $port > active 2>>$out; then
-             :
-           else
-             status=$NOSYNC
-           fi
+            port=$(expr "$host" : '.*:\(.*\)')
+            if [ -n "$port" ]; then
+                port="-p $port"
+                host=$(expr "$host" : '\(.*\):.*')
+            fi
+            echo "getlist -h $host $port" >>$out
+            if getlist -h $host $port >active 2>>$out; then
+                :
+            else
+                status=$NOSYNC
+            fi
         else
-           echo "$GETFTP ftp://$host/$ftp" >>$out
-           $GETFTP ftp://$host/$ftp >>$out 2>&1
-           status=$?
-           if [ "$status" -ne 0 ]; then
-             status=$NOSYNC
-           else
-             case "$ftp" in
-             *.gz)
-                   echo "$GZIP -d active" >>$out
-                   if $GZIP -d active >>$out 2>&1; then
-                     :
-                   else
-                     status=1
-                   fi
-                   ;;
-             *.Z)
-                   echo "$UNCOMPRESS active" >>$out
-                   if $UNCOMPRESS active >>$out 2>&1; then
-                     :
-                   else
-                     status=1
-                   fi
-                   ;;
-             esac
-           fi
+            echo "$GETFTP ftp://$host/$ftp" >>$out
+            $GETFTP ftp://$host/$ftp >>$out 2>&1
+            status=$?
+            if [ "$status" -ne 0 ]; then
+                status=$NOSYNC
+            else
+                case "$ftp" in
+                *.gz)
+                    echo "$GZIP -d active" >>$out
+                    if $GZIP -d active >>$out 2>&1; then
+                        :
+                    else
+                        status=1
+                    fi
+                    ;;
+                *.Z)
+                    echo "$UNCOMPRESS active" >>$out
+                    if $UNCOMPRESS active >>$out 2>&1; then
+                        :
+                    else
+                        status=1
+                    fi
+                    ;;
+                esac
+            fi
         fi
         ;;
     esac
 
     if [ "$status" -ne "$NOSYNC" ]; then
 
-	# detect bad status
-	#
-	if [ "$status" -ne 0 ]; then
-	    echo "FATAL: `date` for $host exit $status" >>$out
+        # detect bad status
+        #
+        if [ "$status" -ne 0 ]; then
+            echo "FATAL: $(date) for $host exit $status" >>$out
             eval $cleanup
-	    exit "$status"
-	fi
+            exit "$status"
+        fi
 
         echo "$ACTSYNC -i $ign $flags ./active" >>$out
         eval "$ACTSYNC -i $ign $flags ./active >$ctlinndcmds 2>>$out"
 
         if [ $? -ne 0 ]; then
-            echo "FATAL: `date` for $host actsync balked" >>$out
+            echo "FATAL: $(date) for $host actsync balked" >>$out
             eval $cleanup
             exit $?
         fi
@@ -219,26 +241,26 @@ for loop in 1 2 3 4 5 6 7 8 9 10; do
         if [ ! -s $ctlinndcmds ]; then
             echo "No changes need to be made" >>$out
         else
-            echo "=-= `date` for $host, updating active" >>$out
+            echo "=-= $(date) for $host, updating active" >>$out
             echo "mod-active $ctlinndcmds" >>$out
             mod-active $ctlinndcmds >>$out 2>&1
 
             if [ $? -ne 0 ]; then
-                echo "FATAL: `date` for $host mod-active FAILED" >>$out
+                echo "FATAL: $(date) for $host mod-active FAILED" >>$out
                 eval $cleanup
-        	exit 1
+                exit 1
             fi
         fi
 
-	# normal exit - all done
-	#
-	echo "=-= `date` for $host, end" >>$out
+        # normal exit - all done
+        #
+        echo "=-= $(date) for $host, end" >>$out
         eval $cleanup
-	exit 0
+        exit 0
     fi
 
     # failed to get the remote active file
-    echo "=-= `date` for $host failed to connect/sync, retrying" >>$out
+    echo "=-= $(date) for $host failed to connect/sync, retrying" >>$out
 
     # wait 6 minutes
     #
@@ -247,6 +269,6 @@ done
 
 # give up
 #
-echo "FATAL: `date` for $host failed to connect/sync 10 times" >>$out 2>&1
+echo "FATAL: $(date) for $host failed to connect/sync 10 times" >>$out 2>&1
 eval $cleanup
 exit 1
diff --git a/backends/nntpsend.in b/backends/nntpsend.in
--- a/backends/nntpsend.in
+++ b/backends/nntpsend.in
@@ -3,27 +3,28 @@
 
 ##  Send news via NNTP by running several innxmit processes in the background.
 ##  Usage:
-##	nntpsend [-acDdlNnpr] [-P portnum] [-s size] [-T limit] [-t timeout]
-##		 [-w delay] [host fqdn] ...
-##	-a		always have innxmit rewrite the batch file (if no size limit)
-##	-c		disable message-ID checking in streaming mode
-##	-D		debug mode, send output to stdout
-##	-d		same as -d, and run innxmit with debug as well
-##	-l		innxmit, log rejected articles
-##	-N		innxmit, disable streaming mode
-##	-n		do not lock for nntpsend
-##	-P portnum	port number to use
-##	-p		run innxmit with -p to prune batch files
-##	-r		innxmit, don't requeue on unexpected error code
-##	-s size		limit the file to size bytes
-##	-T limit	innxmit connection transmit time limit (def: forever)
-##	-t timeout	innxmit timeout to make connection (def: 180)
-##	-w delay	wait delay seconds just before innxmit
-##	host fqdn	send to host and qualified domain (def: nntpsend.ctl)
+##      nntpsend [-acDdlNnpr] [-P portnum] [-s size] [-T limit] [-t timeout]
+##               [-w delay] [host fqdn] ...
+##      -a              always have innxmit rewrite the batch file
+##                                                          (if no size limit)
+##      -c              disable message-ID checking in streaming mode
+##      -D              debug mode, send output to stdout
+##      -d              same as -d, and run innxmit with debug as well
+##      -l              innxmit, log rejected articles
+##      -N              innxmit, disable streaming mode
+##      -n              do not lock for nntpsend
+##      -P portnum      port number to use
+##      -p              run innxmit with -p to prune batch files
+##      -r              innxmit, don't requeue on unexpected error code
+##      -s size         limit the file to size bytes
+##      -T limit        innxmit connection transmit time limit (def: forever)
+##      -t timeout      innxmit timeout to make connection (def: 180)
+##      -w delay        wait delay seconds just before innxmit
+##      host fqdn       send to host and qualified domain (def: nntpsend.ctl)
 ##  If no "host fqdn" pairs appear on the command line, then ${CTLFILE}
 ##  file is read.
 
-PROGNAME=`basename $0`
+PROGNAME=$(basename $0)
 LOCK=${LOCKS}/LOCK.${PROGNAME}
 CTLFILE=${PATHETC}/${PROGNAME}.ctl
 LOG=${MOST_LOGS}/${PROGNAME}.log
@@ -46,99 +47,99 @@ W_SECONDS=
 
 ##  Parse JCL.
 MORETODO=true
-while ${MORETODO} ; do
+while ${MORETODO}; do
     case X"$1" in
     X-a)
-	A_FLAG="-a"
-	;;
+        A_FLAG="-a"
+        ;;
     X-d)
-	D_FLAG="-d"
-	NO_LOG_FLAG="true"
-	;;
+        D_FLAG="-d"
+        NO_LOG_FLAG="true"
+        ;;
     X-D)
-	NO_LOG_FLAG="true"
-	;;
+        NO_LOG_FLAG="true"
+        ;;
     X-l)
-	L_FLAG="-l"
-	;;
+        L_FLAG="-l"
+        ;;
     X-p)
-	P_FLAG="-p"
-	;;
+        P_FLAG="-p"
+        ;;
     X-r)
-	R_FLAG="-r"
-	;;
+        R_FLAG="-r"
+        ;;
     X-N)
-	S_FLAG="-s"
-	;;
+        S_FLAG="-s"
+        ;;
     X-c)
-	C_FLAG="-c"
-	;;
+        C_FLAG="-c"
+        ;;
     X-s)
-	if [ -z "$2" ] ; then
-	    echo "${PROGNAME}: option requires an argument -- s" 1>&2
-	    exit 1
-	fi
-	TRUNC_SIZE="$2"
-	shift
-	;;
+        if [ -z "$2" ]; then
+            echo "${PROGNAME}: option requires an argument -- s" 1>&2
+            exit 1
+        fi
+        TRUNC_SIZE="$2"
+        shift
+        ;;
     X-s*)
-	TRUNC_SIZE="`echo $1 | ${SED} -e 's/-s//'`"
-	;;
+        TRUNC_SIZE="$(echo $1 | ${SED} -e 's/-s//')"
+        ;;
     X-t)
-	if [ -z "$2" ] ; then
-	    echo "${PROGNAME}: option requires an argument -- t" 1>&2
-	    exit 1
-	fi
-	T_FLAG="-t$2"
-	shift
-	;;
+        if [ -z "$2" ]; then
+            echo "${PROGNAME}: option requires an argument -- t" 1>&2
+            exit 1
+        fi
+        T_FLAG="-t$2"
+        shift
+        ;;
     X-t*)
-	T_FLAG="$1"
-	;;
+        T_FLAG="$1"
+        ;;
     X-P)
-	if [ -z "$2" ] ; then
-	    echo "${PROGNAME}: option requires an argument -- P" 1>&2
-	    exit 1
-	fi
-	PP_FLAG="-P$2"
-	shift
-	;;
+        if [ -z "$2" ]; then
+            echo "${PROGNAME}: option requires an argument -- P" 1>&2
+            exit 1
+        fi
+        PP_FLAG="-P$2"
+        shift
+        ;;
     X-P*)
-	PP_FLAG="$1"
-	;;
+        PP_FLAG="$1"
+        ;;
     X-T)
-	if [ -z "$2" ] ; then
-	    echo "${PROGNAME}: option requires an argument -- T" 1>&2
-	    exit 1
-	fi
-	TIMELIMIT="-T$2"
-	shift
-	;;
+        if [ -z "$2" ]; then
+            echo "${PROGNAME}: option requires an argument -- T" 1>&2
+            exit 1
+        fi
+        TIMELIMIT="-T$2"
+        shift
+        ;;
     X-T*)
-	TIMELIMIT="$1"
-	;;
+        TIMELIMIT="$1"
+        ;;
     X-n)
-	NOLOCK=true
-	;;
+        NOLOCK=true
+        ;;
     X-w)
-	if [ -z "$2" ] ; then
-	    echo "${PROGNAME}: option requires an argument -- w" 1>&2
-	    exit 1
-	fi
-	W_SECONDS="$2"
-	shift
-	;;
+        if [ -z "$2" ]; then
+            echo "${PROGNAME}: option requires an argument -- w" 1>&2
+            exit 1
+        fi
+        W_SECONDS="$2"
+        shift
+        ;;
     X--)
-	shift
-	MORETODO=false
-	;;
+        shift
+        MORETODO=false
+        ;;
     X-*)
-	echo "${PROGNAME}: illegal option -- $1" 1>&2
-	exit 1
-	;;
+        echo "${PROGNAME}: illegal option -- $1" 1>&2
+        exit 1
+        ;;
     *)
-	MORETODO=false
-	;;
+        MORETODO=false
+        ;;
     esac
     ${MORETODO} && shift
 done
@@ -158,9 +159,9 @@ INPUT=${TMPDIR}/nntpsend$$
 cp /dev/null ${INPUT}
 while [ $# -gt 0 ]; do
     if [ $# -lt 2 ]; then
-	echo "${PROGNAME}: Bad host/fqdn pair" 1>&2
-	rm -f ${NNTPLOCK}
-	exit 1
+        echo "${PROGNAME}: Bad host/fqdn pair" 1>&2
+        rm -f ${NNTPLOCK}
+        exit 1
     fi
     echo "$1 $2" >>${INPUT}
     shift
@@ -168,14 +169,14 @@ while [ $# -gt 0 ]; do
 done
 
 ##  If nothing specified on the command line, read the control file.
-if [ ! -s ${INPUT} ] ; then
+if [ ! -s ${INPUT} ]; then
     if [ ! -r ${CTLFILE} ]; then
-	echo "${PROGNAME}: cannot read ${CTLFILE}"
-	rm -f ${NNTPLOCK}
-	exit 1
+        echo "${PROGNAME}: cannot read ${CTLFILE}"
+        rm -f ${NNTPLOCK}
+        exit 1
     fi
     ${SED} -e 's/#.*//' -e '/^$/d' -e 's/::\([^:]*\)$/:max:\1/' \
-	-e 's/:/ /g' <${CTLFILE} >${INPUT}
+        -e 's/:/ /g' <${CTLFILE} >${INPUT}
 fi
 
 ##  Go to where the action is.
@@ -202,16 +203,16 @@ export BATCH PROGNAME PARENTPID INNFLAGS
 ##  Loop over all sites.
 while read SITE HOST SIZE_ARG FLAGS; do
     ## Parse the input parameters.
-    if [ -z "${SITE}" -o -z "${HOST}" ] ; then
-	echo "Ignoring bad line: ${SITE} ${HOST} ${SIZE_ARG} ${FLAGS}" 1>&2
-	continue
+    if [ -z "${SITE}" -o -z "${HOST}" ]; then
+        echo "Ignoring bad line: ${SITE} ${HOST} ${SIZE_ARG} ${FLAGS}" 1>&2
+        continue
     fi
 
     ## give up early if we cannot even lock it
     ##
     ## NOTE: This lock is not nntpsend's lock but rather the
-    ##	     lock that the parent shell of innxmit will use.
-    ##	     Later on the child will take the lock from us.
+    ##       lock that the parent shell of innxmit will use.
+    ##       Later on the child will take the lock from us.
     ##
     LOCK="${LOCKS}/LOCK.${SITE}"
     shlock -p $$ -f "${LOCK}" || continue
@@ -219,14 +220,18 @@ while read SITE HOST SIZE_ARG FLAGS; do
     ## Compute the specific parameters for this site.
     test "${SIZE_ARG}" = "max" && SIZE_ARG=
     if [ -n "${TRUNC_SIZE}" ]; then
-	SIZE_ARG="${TRUNC_SIZE}"
+        SIZE_ARG="${TRUNC_SIZE}"
     fi
     ## Parse the SIZE_ARG for either MaxSize-TruncSize or TruncSize
     case "${SIZE_ARG}" in
-    *-*) MAXSIZE="`echo ${SIZE_ARG} | ${SED} -e 's/-.*//'`";
-	 SIZE="`echo ${SIZE_ARG} | ${SED} -e 's/^.*-//'`" ;;
-    *) MAXSIZE="${SIZE_ARG}";
-       SIZE="${SIZE_ARG}" ;;
+    *-*)
+        MAXSIZE="$(echo ${SIZE_ARG} | ${SED} -e 's/-.*//')"
+        SIZE="$(echo ${SIZE_ARG} | ${SED} -e 's/^.*-//')"
+        ;;
+    *)
+        MAXSIZE="${SIZE_ARG}"
+        SIZE="${SIZE_ARG}"
+        ;;
     esac
     D_PARAM=
     R_PARAM=
@@ -237,95 +242,94 @@ while read SITE HOST SIZE_ARG FLAGS; do
     TIMEOUT_PARAM=
     TIMELIMIT_PARAM=
     if [ -z "${FLAGS}" ]; then
-	MORETODO=false
+        MORETODO=false
     else
-	MORETODO=true
-	set -- ${FLAGS}
+        MORETODO=true
+        set -- ${FLAGS}
     fi
-    while ${MORETODO} ; do
-	case "X$1" in
-	X-a)
-	    ;;
-	X-d)
-	    D_PARAM="-d"
-	    ;;
-	X-c)
-	    C_PARAM="-c"
-	    ;;
-	X-p)
-	    P_PARAM="-p"
-	    ;;
-	X-r)
-	    R_PARAM="-r"
-	    ;;
-	X-s)
-	    S_PARAM="-s"
-	    ;;
-	X-l)
-	    L_PARAM="-l"
-	    ;;
-	X-t)
-	    if [ -z "$2" ] ; then
-		echo "${PROGNAME}: option requires an argument -- t" 1>&2
-		rm -f "${NNTPLOCK}" "${LOCK}"
-		exit 1
-	    fi
-	    TIMEOUT_PARAM="-t$2"
-	    shift
-	    ;;
-	X-t*)
-	    TIMEOUT_PARAM="$1"
-	    ;;
-	X-P)
-	    if [ -z "$2" ] ; then
-		echo "${PROGNAME}: option requires an argument -- P" 1>&2
-		rm -f "${NNTPLOCK}" "${LOCK}"
-		exit 1
-	    fi
-	    PP_PARAM="-P$2"
-	    shift
-	    ;;
-	X-P*)
-	    PP_PARAM="$1"
-	    ;;
-	X-T)
-	    if [ -z "$2" ] ; then
-		echo "${PROGNAME}: option requires an argument -- T" 1>&2
-		rm -f "${NNTPLOCK}" "${LOCK}"
-		exit 1
-	    fi
-	    TIMELIMIT_PARAM="-T$2"
-	    shift
-	    ;;
-	X-T*)
-	    TIMELIMIT_PARAM="$1"
-	    ;;
-	X-w)
-	    if [ -z "$2" ] ; then
-		echo "${PROGNAME}: option requires an argument -- w" 1>&2
+    while ${MORETODO}; do
+        case "X$1" in
+        X-a) ;;
+        X-d)
+            D_PARAM="-d"
+            ;;
+        X-c)
+            C_PARAM="-c"
+            ;;
+        X-p)
+            P_PARAM="-p"
+            ;;
+        X-r)
+            R_PARAM="-r"
+            ;;
+        X-s)
+            S_PARAM="-s"
+            ;;
+        X-l)
+            L_PARAM="-l"
+            ;;
+        X-t)
+            if [ -z "$2" ]; then
+                echo "${PROGNAME}: option requires an argument -- t" 1>&2
                 rm -f "${NNTPLOCK}" "${LOCK}"
                 exit 1
-	    fi
-	    W_SECONDS="$2"
-	    shift
+            fi
+            TIMEOUT_PARAM="-t$2"
+            shift
             ;;
-	*)
-	    MORETODO=false
-	    ;;
-	esac
-	${MORETODO} && shift
+        X-t*)
+            TIMEOUT_PARAM="$1"
+            ;;
+        X-P)
+            if [ -z "$2" ]; then
+                echo "${PROGNAME}: option requires an argument -- P" 1>&2
+                rm -f "${NNTPLOCK}" "${LOCK}"
+                exit 1
+            fi
+            PP_PARAM="-P$2"
+            shift
+            ;;
+        X-P*)
+            PP_PARAM="$1"
+            ;;
+        X-T)
+            if [ -z "$2" ]; then
+                echo "${PROGNAME}: option requires an argument -- T" 1>&2
+                rm -f "${NNTPLOCK}" "${LOCK}"
+                exit 1
+            fi
+            TIMELIMIT_PARAM="-T$2"
+            shift
+            ;;
+        X-T*)
+            TIMELIMIT_PARAM="$1"
+            ;;
+        X-w)
+            if [ -z "$2" ]; then
+                echo "${PROGNAME}: option requires an argument -- w" 1>&2
+                rm -f "${NNTPLOCK}" "${LOCK}"
+                exit 1
+            fi
+            W_SECONDS="$2"
+            shift
+            ;;
+        *)
+            MORETODO=false
+            ;;
+        esac
+        ${MORETODO} && shift
     done
     if [ -z "${SIZE}" -o -n "${A_FLAG}" ]; then
-	# rewrite batch file if we do not have a size limit
-	INNFLAGS="-a"
+        # rewrite batch file if we do not have a size limit
+        INNFLAGS="-a"
     else
-	# we have a size limit, let shrinkfile rewrite the file
-	INNFLAGS=
+        # we have a size limit, let shrinkfile rewrite the file
+        INNFLAGS=
     fi
     if [ -n "${D_FLAG}" ]; then
-	INNFLAGS="${INNFLAGS} ${D_FLAG}"
+        INNFLAGS="${INNFLAGS} ${D_FLAG}"
     else
-	test -n "${D_PARAM}" && INNFLAGS="${INNFLAGS} ${D_PARAM}"
+        test -n "${D_PARAM}" && INNFLAGS="${INNFLAGS} ${D_PARAM}"
     fi
     if [ -n "${C_FLAG}" ]; then
         INNFLAGS="${INNFLAGS} ${C_FLAG}"
@@ -333,40 +337,40 @@ while read SITE HOST SIZE_ARG FLAGS; do
         test -n "${C_PARAM}" && INNFLAGS="${INNFLAGS} ${C_PARAM}"
     fi
     if [ -n "${P_FLAG}" ]; then
-	INNFLAGS="${INNFLAGS} ${P_FLAG}"
+        INNFLAGS="${INNFLAGS} ${P_FLAG}"
     else
-	test -n "${P_PARAM}" && INNFLAGS="${INNFLAGS} ${P_PARAM}"
+        test -n "${P_PARAM}" && INNFLAGS="${INNFLAGS} ${P_PARAM}"
     fi
     if [ -n "${L_FLAG}" ]; then
-	INNFLAGS="${INNFLAGS} ${L_FLAG}"
+        INNFLAGS="${INNFLAGS} ${L_FLAG}"
     else
-	test -n "${L_PARAM}" && INNFLAGS="${INNFLAGS} ${L_PARAM}"
+        test -n "${L_PARAM}" && INNFLAGS="${INNFLAGS} ${L_PARAM}"
     fi
     if [ -n "${R_FLAG}" ]; then
-	INNFLAGS="${INNFLAGS} ${R_FLAG}"
+        INNFLAGS="${INNFLAGS} ${R_FLAG}"
     else
-	test -n "${R_PARAM}" && INNFLAGS="${INNFLAGS} ${R_PARAM}"
+        test -n "${R_PARAM}" && INNFLAGS="${INNFLAGS} ${R_PARAM}"
     fi
     if [ -n "${S_FLAG}" ]; then
-	INNFLAGS="${INNFLAGS} ${S_FLAG}"
+        INNFLAGS="${INNFLAGS} ${S_FLAG}"
     else
-	test -n "${S_PARAM}" && INNFLAGS="${INNFLAGS} ${S_PARAM}"
+        test -n "${S_PARAM}" && INNFLAGS="${INNFLAGS} ${S_PARAM}"
     fi
     if [ -n "${T_FLAG}" ]; then
-	INNFLAGS="${INNFLAGS} ${T_FLAG}"
+        INNFLAGS="${INNFLAGS} ${T_FLAG}"
     else
-	test -n "${TIMEOUT_PARAM}" && INNFLAGS="${INNFLAGS} ${TIMEOUT_PARAM}"
+        test -n "${TIMEOUT_PARAM}" && INNFLAGS="${INNFLAGS} ${TIMEOUT_PARAM}"
     fi
     if [ -n "${PP_FLAG}" ]; then
-	INNFLAGS="${INNFLAGS} ${PP_FLAG}"
+        INNFLAGS="${INNFLAGS} ${PP_FLAG}"
     else
-	test -n "${PP_PARAM}" && INNFLAGS="${INNFLAGS} ${PP_PARAM}"
+        test -n "${PP_PARAM}" && INNFLAGS="${INNFLAGS} ${PP_PARAM}"
     fi
     if [ -n "${TIMELIMIT}" ]; then
-	INNFLAGS="${INNFLAGS} ${TIMELIMIT}"
+        INNFLAGS="${INNFLAGS} ${TIMELIMIT}"
     else
-	test -n "${TIMELIMIT_PARAM}" \
-	    && INNFLAGS="${INNFLAGS} ${TIMELIMIT_PARAM}"
+        test -n "${TIMELIMIT_PARAM}" \
+            && INNFLAGS="${INNFLAGS} ${TIMELIMIT_PARAM}"
     fi
 
     ## Flush the buffers for the site now, rather than in the child.
@@ -376,75 +380,75 @@ while read SITE HOST SIZE_ARG FLAGS; do
     ##
     # carry old unfinished work over to this task
     BATCHFILE="${SITE}=n"
-    if [ -f "${SITE}.work" ] ; then
-	cat ${SITE}.work >>"${BATCHFILE}"
-	rm -f "${SITE}.work"
+    if [ -f "${SITE}.work" ]; then
+        cat ${SITE}.work >>"${BATCHFILE}"
+        rm -f "${SITE}.work"
     fi
     # form BATCHFILE to hold the work for this site
     if [ -f "${SITE}" ]; then
-	mv "${SITE}" "${SITE}.work"
-	if ctlinnd -s -t30 flush ${SITE} ; then
-	    cat ${SITE}.work >>"${BATCHFILE}"
-	    rm -f ${SITE}.work
-	else
-	    # flush failed, continue if we have any batch file to work on
-	    echo "${PROGNAME}: bad flush for ${HOST} via ${SITE}"
-	    if [ -f "${BATCHFILE}" ]; then
-		echo "${PROGNAME}: trying ${HOST} via ${SITE} anyway"
-	    else
-		echo "${PROGNAME}: skipping ${HOST} via ${SITE}"
-		rm -f ${LOCK}
-		continue
-	    fi
-	fi
+        mv "${SITE}" "${SITE}.work"
+        if ctlinnd -s -t30 flush ${SITE}; then
+            cat ${SITE}.work >>"${BATCHFILE}"
+            rm -f ${SITE}.work
+        else
+            # flush failed, continue if we have any batch file to work on
+            echo "${PROGNAME}: bad flush for ${HOST} via ${SITE}"
+            if [ -f "${BATCHFILE}" ]; then
+                echo "${PROGNAME}: trying ${HOST} via ${SITE} anyway"
+            else
+                echo "${PROGNAME}: skipping ${HOST} via ${SITE}"
+                rm -f ${LOCK}
+                continue
+            fi
+        fi
     else
-	# nothing to work on, so flush and move on
-	ctlinnd -s -t30 flush ${SITE}
-	echo "${PROGNAME}: file ${BATCH}/${SITE} for ${HOST} not found"
-	if [ -f "${BATCHFILE}" ]; then
-	    echo "${PROGNAME}: trying ${HOST} via ${SITE} anyway"
-	else
-	    echo "${PROGNAME}: skipping ${HOST} via ${SITE}"
-	    rm -f ${LOCK}
-	    continue
-	fi
+        # nothing to work on, so flush and move on
+        ctlinnd -s -t30 flush ${SITE}
+        echo "${PROGNAME}: file ${BATCH}/${SITE} for ${HOST} not found"
+        if [ -f "${BATCHFILE}" ]; then
+            echo "${PROGNAME}: trying ${HOST} via ${SITE} anyway"
+        else
+            echo "${PROGNAME}: skipping ${HOST} via ${SITE}"
+            rm -f ${LOCK}
+            continue
+        fi
     fi
 
     ##  Start sending this site in the background.
     export MAXSIZE SITE HOST PROGNAME PARENTPID SIZE TMPDIR LOCK BATCHFILE W_SECONDS
     sh -c '
-	# grab the lock from the parent
-	#
-	# This is safe because only the parent will have locked
-	# the site.  We break the lock and reclaim it.
-	rm -f ${LOCK}
-	trap "rm -f ${LOCK} ; exit 1" 1 2 3 15
-	shlock -p $$ -f ${LOCK} || {
-	    WHY="`cat ${LOCK}`"
-	    echo "${PROGNAME}: [${PARENTPID}:$$] ${SITE} locked ${WHY} `date`"
-	    exit
-	}
-	# process the site BATCHFILE
-	if [ -f "${BATCHFILE}" ]; then
-	    test -n "${SIZE}" && shrinkfile -m${MAXSIZE} -s${SIZE} -v ${BATCHFILE}
-	    if [ -s ${BATCHFILE} ] ; then
-		if [ -n "${W_SECONDS}" ] ; then
-		    echo "${PROGNAME}: [${PARENTPID}:$$] sleeping ${W_SECONDS} seconds before ${SITE}"
-		    sleep "${W_SECONDS}"
-		fi
-		echo "${PROGNAME}: [${PARENTPID}:$$] begin ${SITE} `date`"
-		echo "${PROGNAME}: [${PARENTPID}:$$] innxmit ${INNFLAGS} ${HOST} ..."
-		eval innxmit ${INNFLAGS} ${HOST} ${BATCH}/${BATCHFILE}
-		echo "${PROGNAME}: [${PARENTPID}:$$] end ${SITE} `date`"
-	    else
-		rm -f ${BATCHFILE}
-	    fi
-	else
-	    echo "${PROGNAME}: file ${BATCH}/${BATCHFILE} for ${HOST} not found"
-	fi
-	rm -f ${LOCK}
+        # grab the lock from the parent
+        #
+        # This is safe because only the parent will have locked
+        # the site.  We break the lock and reclaim it.
+        rm -f ${LOCK}
+        trap "rm -f ${LOCK} ; exit 1" 1 2 3 15
+        shlock -p $$ -f ${LOCK} || {
+            WHY="$(cat ${LOCK})"
+            echo "${PROGNAME}: [${PARENTPID}:$$] ${SITE} locked ${WHY} $(date)"
+            exit
+        }
+        # process the site BATCHFILE
+        if [ -f "${BATCHFILE}" ]; then
+            test -n "${SIZE}" && shrinkfile -m${MAXSIZE} -s${SIZE} -v ${BATCHFILE}
+            if [ -s ${BATCHFILE} ]; then
+                if [ -n "${W_SECONDS}" ]; then
+                    echo "${PROGNAME}: [${PARENTPID}:$$] sleeping ${W_SECONDS} seconds before ${SITE}"
+                    sleep "${W_SECONDS}"
+                fi
+                echo "${PROGNAME}: [${PARENTPID}:$$] begin ${SITE} $(date)"
+                echo "${PROGNAME}: [${PARENTPID}:$$] innxmit ${INNFLAGS} ${HOST} ..."
+                eval innxmit ${INNFLAGS} ${HOST} ${BATCH}/${BATCHFILE}
+                echo "${PROGNAME}: [${PARENTPID}:$$] end ${SITE} $(date)"
+            else
+                rm -f ${BATCHFILE}
+            fi
+        else
+            echo "${PROGNAME}: file ${BATCH}/${BATCHFILE} for ${HOST} not found"
+        fi
+        rm -f ${LOCK}
     ' &
-done < ${INPUT}
+done <${INPUT}
 
 ##  Release the nntpsend lock and clean up before we wait on child processes.
 if [ -z "${NOLOCK}" ]; then
diff --git a/backends/sendxbatches.in b/backends/sendxbatches.in
--- a/backends/sendxbatches.in
+++ b/backends/sendxbatches.in
@@ -10,30 +10,28 @@
 ##  TODO: - we should check the amount of queued batches for the site,
 ##          to prevent disk overflow due to unreachable sites.
 
-if [ $# -lt 3 ]
-then
-	echo "usage: $0 <sitename> <hostname> <xbatch file name> ..."
-	exit 1
+if [ $# -lt 3 ]; then
+    echo "usage: $0 <sitename> <hostname> <xbatch file name> ..."
+    exit 1
 fi
 
 LOCK=${LOCKS}/LOCK.sendxbatches
 shlock -p $$ -f ${LOCK}
-if [ $? -ne 0 ]
-then
-	echo Locked by `cat ${LOCK}`
-	exit 1
+if [ $? -ne 0 ]; then
+    echo Locked by $(cat ${LOCK})
+    exit 1
 fi
 
 trap 'rm -f ${LOCK} ; exit 1' 1 2 3 15
 site="$1"
 host="$2"
-shift; shift
+shift
+shift
 
 ctlinnd -s flush "$site"
-if [ $? -ne 0 ]
-then
-	echo "ctlinnd flush $site failed."
-	exit 1
+if [ $? -ne 0 ]; then
+    echo "ctlinnd flush $site failed."
+    exit 1
 fi
 sleep 5
 $NEWSBIN/innxbatch -D -v "$host" $*
diff --git a/scripts/rc.news.in b/scripts/rc.news.in
--- a/scripts/rc.news.in
+++ b/scripts/rc.news.in
@@ -7,28 +7,25 @@
 ##  Or to stop INN:
 ##     su news -s /bin/sh -c '/path/to/rc.news stop'
 
-
 if [ "x${NEWSUSER}" = "x" ]; then
     echo "$0 does not manage to access inn.conf values."
     exit 1
 fi
 
 # Ensure the script is really run as the news user.  Bail out otherwise.
-CURRENT_UID=`whoami 2>/dev/null || ${PERL} -e 'print scalar getpwuid($>)'`
+CURRENT_UID=$(whoami 2>/dev/null || ${PERL} -e 'print scalar getpwuid($>)')
 if [ "x${CURRENT_UID}" != "x${NEWSUSER}" ]; then
     echo "$0 must be run as user ${NEWSUSER}, not ${CURRENT_UID}."
     exit 1
 fi
 
-waitforpid()
-{
+waitforpid() {
     i=12
-    while [ $i -gt 0 ];
-    do
+    while [ $i -gt 0 ]; do
         kill -0 $1 2>/dev/null || break
-	sleep 5
-	printf "."
-	i=`expr $i - 1`
+        sleep 5
+        printf "."
+        i=$(expr $i - 1)
     done
     printf "\n"
 }
@@ -37,58 +34,58 @@ case X"$1" in
 Xstop)
     # Stop cnfsstat (if running)
     if [ -f ${PATHRUN}/cnfsstat.pid ]; then
-	kill `cat ${PATHRUN}/cnfsstat.pid`
-	rm -f ${PATHRUN}/cnfsstat.pid
+        kill $(cat ${PATHRUN}/cnfsstat.pid)
+        rm -f ${PATHRUN}/cnfsstat.pid
     fi
 
     # Stop innwatch (if running)
     if [ -f $WATCHPID ]; then
-	kill `cat $WATCHPID`
-	rm -f $WATCHPID ${LOCKS}/LOCK.innwatch
+        kill $(cat $WATCHPID)
+        rm -f $WATCHPID ${LOCKS}/LOCK.innwatch
     fi
 
     printf "Stopping innd: "
     ${PATHBIN}/ctlinnd shutdown 'rc.news stop'
 
     # Wait for innd to exit (up to 60 sec)
-    pid=`cat ${SERVERPID} 2>/dev/null`
+    pid=$(cat ${SERVERPID} 2>/dev/null)
     if [ "$pid" != "" ]; then
-	waitforpid $pid
+        waitforpid $pid
     else
-	printf "\n"
+        printf "\n"
     fi
 
     case "$OVMETHOD" in
     ovdb)
-	# Turn off ovdb support procs, and close the DB environment
-	if [ -f ${PATHRUN}/ovdb_server.pid ]; then
-	    pid=`cat ${PATHRUN}/ovdb_server.pid 2>/dev/null`
-	    if [ "$pid" != "" ]; then
-		printf "Stopping ovdb_server: "
-		kill $pid
-		waitforpid $pid
-	    fi
-	fi
-	if [ -f ${PATHRUN}/ovdb_monitor.pid ]; then
-	    pid=`cat ${PATHRUN}/ovdb_monitor.pid 2>/dev/null`
-	    if [ "$pid" != "" ]; then
-		printf "Stopping ovdb_monitor: "
-		kill $pid
-		waitforpid $pid
-	    fi
-	fi
-	;;
+        # Turn off ovdb support procs, and close the DB environment
+        if [ -f ${PATHRUN}/ovdb_server.pid ]; then
+            pid=$(cat ${PATHRUN}/ovdb_server.pid 2>/dev/null)
+            if [ "$pid" != "" ]; then
+                printf "Stopping ovdb_server: "
+                kill $pid
+                waitforpid $pid
+            fi
+        fi
+        if [ -f ${PATHRUN}/ovdb_monitor.pid ]; then
+            pid=$(cat ${PATHRUN}/ovdb_monitor.pid 2>/dev/null)
+            if [ "$pid" != "" ]; then
+                printf "Stopping ovdb_monitor: "
+                kill $pid
+                waitforpid $pid
+            fi
+        fi
+        ;;
     ovsqlite)
         # Turn off ovsqlite support proc, and close the DB environment
-	if [ -f "${PATHRUN}"/ovsqlite.pid ]; then
-	    pid=`cat "${PATHRUN}"/ovsqlite.pid 2>/dev/null`
-	    if [ "$pid" != "" ]; then
-		printf "Stopping ovsqlite-server: "
-		kill $pid
-		waitforpid $pid
-	    fi
-	fi
-	;;
+        if [ -f "${PATHRUN}"/ovsqlite.pid ]; then
+            pid=$(cat "${PATHRUN}"/ovsqlite.pid 2>/dev/null)
+            if [ "$pid" != "" ]; then
+                printf "Stopping ovsqlite-server: "
+                kill $pid
+                waitforpid $pid
+            fi
+        fi
+        ;;
     esac
 
     if [ -f ${PATHBIN}/rc.news.local ]; then
@@ -102,82 +99,80 @@ Xstop)
     rm -f ${PATHRUN}/ovsqlite.pid
 
     exit 0
-;;
+    ;;
 esac
 
 ##  Pick ${INND} or ${INNDSTART}
 WHAT=${INND}
 
-MAIL="${MAILCMD} -s 'Boot-time Usenet warning on `hostname`' ${NEWSMASTER}"
+MAIL="${MAILCMD} -s 'Boot-time Usenet warning on $(hostname)' ${NEWSMASTER}"
 
 ##  RFLAG is set below; set INNFLAGS in inn.conf(5)
 RFLAG=""
 
 ##  Be sure ${PATHRUN} exists and is writable.
-if [ ! -w ${PATHRUN} ] ; then
+if [ ! -w ${PATHRUN} ]; then
     echo "No ${PATHRUN} directory writable by the news user found!"
     exit 1
 fi
 
 ##  Clean shutdown or already running?
-if [ -f ${SERVERPID} ] ; then
-    if kill -0 `cat ${SERVERPID}` 2>/dev/null; then
-	echo 'INND is running'
-	exit 0
+if [ -f ${SERVERPID} ]; then
+    if kill -0 $(cat ${SERVERPID}) 2>/dev/null; then
+        echo 'INND is running'
+        exit 0
     fi
     echo 'INND: PID file exists -- unclean shutdown!'
     RFLAG="-r"
 fi
 
-if [ ! -f ${PATHDB}/.news.daily ] ; then
-    case `find ${PATHBIN}/innd -mtime +1 -print 2>/dev/null` in
-    "")
-	;;
+if [ ! -f ${PATHDB}/.news.daily ]; then
+    case $(find ${PATHBIN}/innd -mtime +1 -print 2>/dev/null) in
+    "") ;;
     *)
-	echo 'No .news.daily file; need to run news.daily?' | eval ${MAIL}
-	;;
+        echo 'No .news.daily file; need to run news.daily?' | eval ${MAIL}
+        ;;
     esac
 else
-    case `find ${PATHDB}/.news.daily -mtime +1 -print 2>/dev/null` in
-    "")
-	;;
+    case $(find ${PATHDB}/.news.daily -mtime +1 -print 2>/dev/null) in
+    "") ;;
     *)
-	echo 'Old .news.daily file; need to run news.daily?' | eval ${MAIL}
-	;;
+        echo 'Old .news.daily file; need to run news.daily?' | eval ${MAIL}
+        ;;
     esac
 fi
 
 ##  Active file recovery.
-if [ ! -s ${ACTIVE} ] ; then
-    if [ -s ${NEWACTIVE} ] ; then
-	mv ${NEWACTIVE} ${ACTIVE}
+if [ ! -s ${ACTIVE} ]; then
+    if [ -s ${NEWACTIVE} ]; then
+        mv ${NEWACTIVE} ${ACTIVE}
     else
-	if [ -s ${OLDACTIVE} ] ; then
-	    cp ${OLDACTIVE} ${ACTIVE}
-	else
-	    echo 'INND: No active file!'
-	    exit 1
-	fi
+        if [ -s ${OLDACTIVE} ]; then
+            cp ${OLDACTIVE} ${ACTIVE}
+        else
+            echo 'INND: No active file!'
+            exit 1
+        fi
     fi
     RFLAG="-r"
     # You might want to rebuild the DBZ database, too:
     #cd ${PATHDB} \
-    #		&& makehistory -r \
-    #		&& mv history.n.dir history.dir \
-    #		&& mv history.n.index history.index \
-    #		&& mv history.n.hash history.hash
+    #    && makehistory -r \
+    #    && mv history.n.dir history.dir \
+    #    && mv history.n.index history.index \
+    #    && mv history.n.hash history.hash
 fi
 
 ##  Overview data was rebuilt, and also active needs to be renumbered
-if [ -f ${PATHRUN}/.rebuildoverview ] ; then
+if [ -f ${PATHRUN}/.rebuildoverview ]; then
     echo 'INND: overview was rebuilt, and active needs to be renumbered!'
     RFLAG="-r"
 fi
 
 ##  Remove temporary batchfiles and lock files.
-( cd ${BATCH} && rm -f bch* )
-( cd ${LOCKS} && rm -f LOCK* )
-( cd ${TEMPSOCKDIR} && rm -f ${TEMPSOCK} )
+(cd ${BATCH} && rm -f bch*)
+(cd ${LOCKS} && rm -f LOCK*)
+(cd ${TEMPSOCKDIR} && rm -f ${TEMPSOCK})
 rm -f ${NEWSCONTROL} ${NNTPCONNECT} ${SERVERPID} ${PATHRUN}/.rebuildoverview
 
 case "$OVMETHOD" in
@@ -185,8 +180,8 @@ ovdb)
     # Initialize ovdb.  Must be done before starting innd.
     echo 'Starting ovdb.'
     ovdb_init || {
-	echo "Can't initialize ovdb (check news.err for OVDB messages)"
-	exit 1
+        echo "Can't initialize ovdb (check news.err for OVDB messages)"
+        exit 1
     }
     sleep 1
     ;;
@@ -209,29 +204,29 @@ fi
 # Gee, looks like lisp, doesn't it?
 ${DOINNWATCH} && {
     echo "Scheduled start of ${INNWATCH}."
-    ${INNWATCH} -i 60 > /dev/null &
+    ${INNWATCH} -i 60 >/dev/null &
 }
 
 ${DOCNFSSTAT} && {
     echo "Scheduled start of cnfsstat."
-    ${PATHBIN}/cnfsstat -i 60 -s -l -P > /dev/null &
+    ${PATHBIN}/cnfsstat -i 60 -s -l -P >/dev/null &
 }
 
 RMFILE=${MOST_LOGS}/expire.rm
 for F in ${RMFILE} ${RMFILE}.*; do
     if [ -f $F ] && [ -s $F ]; then
-	echo "Removing articles from pre-downtime expire run (${F})."
-	(
-	    echo 'System shut down during expire.' \
-		'Unlinking articles listed in'
-	    echo ${F}
-	) | eval ${MAIL}
-	${PATHBIN}/expirerm ${F}
+        echo "Removing articles from pre-downtime expire run (${F})."
+        (
+            echo 'System shut down during expire.' \
+                'Unlinking articles listed in'
+            echo ${F}
+        ) | eval ${MAIL}
+        ${PATHBIN}/expirerm ${F}
     fi
 done &
 
 # Run any additional local startup commands.
-if [ -f ${PATHBIN}/rc.news.local ] ; then
+if [ -f ${PATHBIN}/rc.news.local ]; then
     ${PATHBIN}/rc.news.local start
 fi
 
diff --git a/scripts/scanlogs.in b/scripts/scanlogs.in
--- a/scripts/scanlogs.in
+++ b/scripts/scanlogs.in
@@ -5,7 +5,7 @@
 ##  Used by news.daily.
 ##
 ##  Optional arguments:
-##	norotate	Do not rotate logfiles.
+##      norotate      Do not rotate logfiles.
 
 ##  Directory where old log files are kept.
 OLD=${MOST_LOGS}/OLD
@@ -25,11 +25,11 @@ MAXERRLINES=50
 CONTROLBATCH=${MOST_LOGS}/controlbatch.log
 INNFEEDCONF=${PATHETC}/innfeed.conf
 if [ -f "${INNFEEDCONF}" ]; then
-    INNFEEDLOG=`${AWK} '{gsub(/:|#/, " & ")} {if ($1 == "log-file" && $2 == ":") print $3}' ${INNFEEDCONF}`
-    INNFEEDPIDFILE=`${AWK} '{gsub(/:|#/, " & ")} {if ($1 == "pid-file" && $2 == ":") print $3}' ${INNFEEDCONF}`
+    INNFEEDLOG=$(${AWK} '{gsub(/:|#/, " & ")} {if ($1 == "log-file" && $2 == ":") print $3}' ${INNFEEDCONF})
+    INNFEEDPIDFILE=$(${AWK} '{gsub(/:|#/, " & ")} {if ($1 == "pid-file" && $2 == ":") print $3}' ${INNFEEDCONF})
 fi
 INNFEED=
-for F in "${INNFEEDLOG}" ; do
+for F in "${INNFEEDLOG}"; do
     test -f "${MOST_LOGS}/${F}" && INNFEED="${INNFEED} ${MOST_LOGS}/${F}"
 done
 test -z "${INNFEED}" && test -f "${MOST_LOGS}/innfeed.log" && INNFEED="${MOST_LOGS}/innfeed.log"
@@ -55,19 +55,19 @@ CONTROL_LOG=${MOST_LOGS}/control.log
 CONTROL_DATA=
 test -f ${MOST_LOGS}/newgroup.log && CONTROL_DATA=${MOST_LOGS}/newgroup.log
 test -f ${MOST_LOGS}/rmgroup.log \
-	&& CONTROL_DATA="${CONTROL_DATA} ${MOST_LOGS}/rmgroup.log"
+    && CONTROL_DATA="${CONTROL_DATA} ${MOST_LOGS}/rmgroup.log"
 
 ##  Build up the list of log files to process.
 LOGS="${ERRLOG} ${LOG} ${ACTIVEFILE} ${EXPLOG} ${SYSLOGS} ${UNWANTED_LOG}"
 
-for F in ${LIVEFILES} ; do
+for F in ${LIVEFILES}; do
     test -n "${F}" -a -f "${F}" && LOGS="${LOGS} ${F}"
 done
 
 test -n "${CONTROL_DATA}" && LOGS="${LOGS} ${CONTROL_LOG}"
 
 for F in checkgroups default ihave newgroup rmgroup sendme sendsys \
-	senduuname version miscctl badcontrol failedpgp badpgp; do
+    senduuname version miscctl badcontrol failedpgp badpgp; do
     test -f ${MOST_LOGS}/${F}.log && LOGS="${LOGS} ${MOST_LOGS}/${F}.log"
 done
 
@@ -78,34 +78,33 @@ LOCK=${LOCKS}/LOCK.${PROGNAME}
 ROTATE=true
 
 ##  Parse JCL.
-for I
-do
+for I; do
     case "X${I}" in
     Xnorotate)
-	ROTATE=false
-	;;
+        ROTATE=false
+        ;;
     *)
-	echo "Unknown flag ${I}" 1>&2
-	exit 1
-	;;
+        echo "Unknown flag ${I}" 1>&2
+        exit 1
+        ;;
     esac
 done
 
 ##  Make sure every log exists.
-for F in ${LOGS} ; do
+for F in ${LOGS}; do
     test ! -f ${F} && touch ${F}
 done
 
 ##  Rotate the logs?
-if ${ROTATE} ; then
+if ${ROTATE}; then
     ##  Lock out others.
     shlock -p $$ -f ${LOCK} || {
-	echo "$0: Locked by `cat ${LOCK}`"
-	exit 1
+        echo "$0: Locked by $(cat ${LOCK})"
+        exit 1
     }
     trap "rm -f ${LOCK}; exit 0" 1 2 3 15
 
-    HERE=`pwd`
+    HERE=$(pwd)
     cd ${MOST_LOGS}
     test ! -d ${OLD} && mkdir ${OLD}
 
@@ -115,47 +114,47 @@ if ${ROTATE} ; then
 
     ##  First, flush log files to be sure everything has been recorded
     ##  before rotating them.
-    OUTPUT=`ctlinnd flushlogs 2>&1`
+    OUTPUT=$(ctlinnd flushlogs 2>&1)
     if [ "$OUTPUT" != "Ok" -a "$OUTPUT" != "In debug mode" ]; then
-	echo "$OUTPUT"
-	echo 'Cannot flush logs.'
-	rm -f ${LOCK}
-	exit 1
+        echo "$OUTPUT"
+        echo 'Cannot flush logs.'
+        rm -f ${LOCK}
+        exit 1
     fi
 
     ##  Make sure these .old files exist, in case innd is down.
-    for F in ${LOG} ${ERRLOG} ; do
-	if [ ! -f ${F}.old ]; then
-	    rm -f ${F}.old
-	    cp ${F} ${F}.old
-	    cat /dev/null >${F}
-	fi
+    for F in ${LOG} ${ERRLOG}; do
+        if [ ! -f ${F}.old ]; then
+            rm -f ${F}.old
+            cp ${F} ${F}.old
+            cat /dev/null >${F}
+        fi
     done
 
     ##  Copy syslog files, truncating old inode since syslog has it open.
     for F in ${SYSLOGS}; do
-	rm -f ${F}.old
-	cp ${F} ${F}.old
-	cat /dev/null >${F}
+        rm -f ${F}.old
+        cp ${F} ${F}.old
+        cat /dev/null >${F}
     done
     ctlinnd -s logmode
 
     ##  Make a copy of the active file.
-    if [ -n ${ACTIVEFILE} ] ; then
-	BASE=`basename ${ACTIVEFILE}`
-	rm -f ${OLD}/${BASE}.old
-	cp ${ACTIVEFILE} ${OLD}/${BASE}.old
+    if [ -n ${ACTIVEFILE} ]; then
+        BASE=$(basename ${ACTIVEFILE})
+        rm -f ${OLD}/${BASE}.old
+        cp ${ACTIVEFILE} ${OLD}/${BASE}.old
     fi
 
     ##  These are live files, so use link rather than copy.
-    for F in ${LIVEFILES} ; do
-	if [ -f ${F} ]; then
-	    rm -f ${F}.old ${F}.new
-	    ln ${F} ${F}.old
-	    touch ${F}.new
-	    chmod 0660 ${F}.new
-	    mv ${F}.new ${F}
-	fi
+    for F in ${LIVEFILES}; do
+        if [ -f ${F} ]; then
+            rm -f ${F}.old ${F}.new
+            ln ${F} ${F}.old
+            touch ${F}.new
+            chmod 0660 ${F}.new
+            mv ${F}.new ${F}
+        fi
     done
 
     ##  Tally control messages if we logged them.
@@ -164,75 +163,75 @@ if ${ROTATE} ; then
     ##  Find out the PID of innfeed now and not at the beginning of scanlogs
     ##  because it is restarted when running ctlinnd flushlogs.
     INNFEEDPID=
-    for F in "${INNFEEDPIDFILE}" ; do
-        test -f "${PATHRUN}/${F}" && INNFEEDPID=`cat "${PATHRUN}/${F}"`
+    for F in "${INNFEEDPIDFILE}"; do
+        test -f "${PATHRUN}/${F}" && INNFEEDPID=$(cat "${PATHRUN}/${F}")
     done
-    test -z "${INNFEEDPID}" && test -f "${PATHRUN}/innfeed.pid" && INNFEEDPID=`cat "${PATHRUN}/innfeed.pid"`
+    test -z "${INNFEEDPID}" && test -f "${PATHRUN}/innfeed.pid" && INNFEEDPID=$(cat "${PATHRUN}/innfeed.pid")
 
     ##  Send a HUP signal to innfeed so that it reopens its log files.
     if [ ! -z ${INNFEEDPID} ]; then
-        kill -HUP ${INNFEEDPID} > /dev/null 2>&1
+        kill -HUP ${INNFEEDPID} >/dev/null 2>&1
     fi
 
     ${PAUSED} && ctlinnd -s go "Flushing log and syslog files" 2>&1
 
     cd ${OLD}
     for F in ${LOGS}; do
-	##  Process the current (just-flushed) log.
-	BASE=`basename ${F}`
-	rm -f ${OLD}/${BASE}
-	case ${F} in
-	${SYSLOG_CRIT}|${SYSLOG_ERR}|${ERRLOG}|${LOG}|${SYSLOG_NOTICE})
-	    ##  Make a link that can be deleted (since if not rotating
-	    ##  we delete the copy that is made in ${TMPDIR}).
-	    mv ${F}.old ${OLD}/${BASE}
-	    rm -f ${OLD}/${BASE}.0
-	    ln ${OLD}/${BASE} ${OLD}/${BASE}.0
-	    ;;
-	${ACTIVEFILE})
-	    mv ${BASE}.old ${OLD}/${BASE}
-	    ;;
-	${UNWANTED_LOG})
-	    ##  Rotate and compress the file.
-	    BASE=`basename ${F}`
-	    if [ ! -f ${BASE} -a -f ../${BASE} ]; then
-		cp ../${BASE} ${BASE}
-		chmod 0440 ${BASE}
-	    fi
-	    if [ -f ${BASE} ]; then
-		${LOG_COMPRESS} <${BASE} >${BASE}.0${Z} && rm -f ${BASE}
-		chmod 0440 ${BASE}.0${Z}
+        ##  Process the current (just-flushed) log.
+        BASE=$(basename ${F})
+        rm -f ${OLD}/${BASE}
+        case ${F} in
+        ${SYSLOG_CRIT} | ${SYSLOG_ERR} | ${ERRLOG} | ${LOG} | ${SYSLOG_NOTICE})
+            ##  Make a link that can be deleted (since if not rotating
+            ##  we delete the copy that is made in ${TMPDIR}).
+            mv ${F}.old ${OLD}/${BASE}
+            rm -f ${OLD}/${BASE}.0
+            ln ${OLD}/${BASE} ${OLD}/${BASE}.0
+            ;;
+        ${ACTIVEFILE})
+            mv ${BASE}.old ${OLD}/${BASE}
+            ;;
+        ${UNWANTED_LOG})
+            ##  Rotate and compress the file.
+            BASE=$(basename ${F})
+            if [ ! -f ${BASE} -a -f ../${BASE} ]; then
+                cp ../${BASE} ${BASE}
+                chmod 0440 ${BASE}
+            fi
+            if [ -f ${BASE} ]; then
+                ${LOG_COMPRESS} <${BASE} >${BASE}.0${Z} && rm -f ${BASE}
+                chmod 0440 ${BASE}.0${Z}
 
-		##  Do rotation.
-		if [ X${LOGCYCLES} = X ]; then       
-		    LOGCYCLES=3
-		fi
-		EXT=${LOGCYCLES}
-		rm -f ${BASE}.${LOGCYCLES}${Z}
-		while [ ${EXT} -gt 0 ] ; do
-		    NEXT=${EXT}
-		    EXT=`expr ${EXT} - 1`
-		    test -f ${BASE}.${EXT}${Z} \
-			&& rm -f ${BASE}.${NEXT}${Z} \
-			&& mv ${BASE}.${EXT}${Z} ${BASE}.${NEXT}${Z}
-		done
-	    fi
-	    ##  innreport assumes where unwanted.log exists, so leave it
-	    ##  and process later.
-	    ;;
-	*)
-	    if [ -f ${F}.old ]; then
-		mv ${F}.old ${OLD}/${BASE}
-	    else
-		rm -f ${OLD}/${BASE} ${F}.new
-		touch ${F}.new
-		chmod 0660 ${F}.new
-		ln ${F} ${F}.old
-		mv ${F}.new ${F}
-		mv ${F}.old ${OLD}/${BASE}
-	    fi
-	    ;;
-	esac
+                ##  Do rotation.
+                if [ X${LOGCYCLES} = X ]; then
+                    LOGCYCLES=3
+                fi
+                EXT=${LOGCYCLES}
+                rm -f ${BASE}.${LOGCYCLES}${Z}
+                while [ ${EXT} -gt 0 ]; do
+                    NEXT=${EXT}
+                    EXT=$(expr ${EXT} - 1)
+                    test -f ${BASE}.${EXT}${Z} \
+                        && rm -f ${BASE}.${NEXT}${Z} \
+                        && mv ${BASE}.${EXT}${Z} ${BASE}.${NEXT}${Z}
+                done
+            fi
+            ##  innreport assumes where unwanted.log exists, so leave it
+            ##  and process later.
+            ;;
+        *)
+            if [ -f ${F}.old ]; then
+                mv ${F}.old ${OLD}/${BASE}
+            else
+                rm -f ${OLD}/${BASE} ${F}.new
+                touch ${F}.new
+                chmod 0660 ${F}.new
+                ln ${F} ${F}.old
+                mv ${F}.new ${F}
+                mv ${F}.old ${OLD}/${BASE}
+            fi
+            ;;
+        esac
     done
     cd ${HERE}
 
@@ -242,10 +241,10 @@ else
 
     ##  Make a snapshot of what we need for below.
     ctlinnd -s pause "Snapshot log and syslog files" 2>&1
-    for F in ${SYSLOG_CRIT} ${SYSLOG_ERR} ${ERRLOG} ${LOG} ${SYSLOG_NOTICE} ; do
-	BASE=`basename ${F}`
-	rm -f ${OLD}/${BASE}.0
-	cp ${F} ${OLD}/${BASE}.0
+    for F in ${SYSLOG_CRIT} ${SYSLOG_ERR} ${ERRLOG} ${LOG} ${SYSLOG_NOTICE}; do
+        BASE=$(basename ${F})
+        rm -f ${OLD}/${BASE}.0
+        cp ${F} ${OLD}/${BASE}.0
     done
     ctlinnd -s go "Snapshot log and syslog files" 2>&1
 fi
@@ -255,9 +254,9 @@ fi
 ##
 
 ##  Display syslog critical messages.
-BASE=`basename ${SYSLOG_CRIT}`
+BASE=$(basename ${SYSLOG_CRIT})
 OLD_SYSLOG=${OLD}/${BASE}.0
-if [ -s ${OLD_SYSLOG} ] ; then
+if [ -s ${OLD_SYSLOG} ]; then
     echo Syslog critical messages:
     cat ${OLD_SYSLOG} | head -n ${MAXERRLINES}
     echo ---------
@@ -266,9 +265,9 @@ fi
 rm -f ${OLD_SYSLOG}
 
 ##  Display syslog error messages.
-BASE=`basename ${SYSLOG_ERR}`
+BASE=$(basename ${SYSLOG_ERR})
 OLD_SYSLOG=${OLD}/${BASE}.0
-if [ -s ${OLD_SYSLOG} ] ; then
+if [ -s ${OLD_SYSLOG} ]; then
     echo Syslog error messages:
     cat ${OLD_SYSLOG} | head -n ${MAXERRLINES}
     echo ---------
@@ -277,9 +276,9 @@ fi
 rm -f ${OLD_SYSLOG}
 
 ##  Display error log.
-BASE=`basename ${ERRLOG}`
+BASE=$(basename ${ERRLOG})
 OLD_ERRLOG=${OLD}/${BASE}.0
-if [ -s ${OLD_ERRLOG} ] ; then
+if [ -s ${OLD_ERRLOG} ]; then
     echo Error log:
     cat ${OLD_ERRLOG} | head -n ${MAXERRLINES}
     echo ---------
@@ -288,16 +287,16 @@ fi
 rm -f ${OLD_ERRLOG}
 
 ##  Scan for various problems in articles we were offered or sent...
-BASE=`basename ${LOG}`
+BASE=$(basename ${LOG})
 OLD_LOG=${OLD}/${BASE}.0
 
 ##  and summarize syslog information.
-BASE=`basename ${SYSLOG_NOTICE}`
+BASE=$(basename ${SYSLOG_NOTICE})
 OLD_SYSLOG=${OLD}/${BASE}.0
 INNREPORT=${TMPDIR}/innreport$$
-if [ -s ${OLD_SYSLOG} -o -s ${OLD_LOG} ] ; then
-    ${PATHBIN}/innreport -f ${PATHETC}/innreport.conf ${OLD_SYSLOG} ${OLD_LOG} > ${INNREPORT}
-    if [ -s ${INNREPORT} ] ; then
+if [ -s ${OLD_SYSLOG} -o -s ${OLD_LOG} ]; then
+    ${PATHBIN}/innreport -f ${PATHETC}/innreport.conf ${OLD_SYSLOG} ${OLD_LOG} >${INNREPORT}
+    if [ -s ${INNREPORT} ]; then
         cat ${INNREPORT}
         echo ---------
         echo ''
@@ -307,46 +306,46 @@ rm -f ${OLD_LOG} ${OLD_SYSLOG} ${INNREPORT}
 
 ##  Now that innreport has finished, we can move unwanted.log.  This
 ##  file is not reset because it keeps the count of unwanted newsgroups.
-if ${ROTATE} ; then
-    BASE=`basename ${UNWANTED_LOG}`
+if ${ROTATE}; then
+    BASE=$(basename ${UNWANTED_LOG})
     if [ -f ${UNWANTED_LOG}.old ]; then
-	mv ${UNWANTED_LOG}.old ${OLD}/${BASE}
+        mv ${UNWANTED_LOG}.old ${OLD}/${BASE}
     else
-	rm -f ${OLD}/${BASE}
-	cp ${UNWANTED_LOG} ${OLD}/${BASE}
-	chmod 0660 ${OLD}/${BASE}
+        rm -f ${OLD}/${BASE}
+        cp ${UNWANTED_LOG} ${OLD}/${BASE}
+        chmod 0660 ${OLD}/${BASE}
     fi
 fi
 
 ##  Compress and rotate the logs.
-if ${ROTATE} ; then
+if ${ROTATE}; then
     cd ${OLD}
-    if [ X${LOGCYCLES} = X ]; then       
+    if [ X${LOGCYCLES} = X ]; then
         LOGCYCLES=3
     fi
-    for F in ${LOGS} ; do
-	##  Skip if it's unwanted.log, since it's already rotated.
-	if [ ${F} = ${UNWANTED_LOG} ]; then
-	    continue
-	fi
-	##  Skip if file doesn't exist.
-	BASE=`basename ${F}`
-	test -f ${BASE} || continue
+    for F in ${LOGS}; do
+        ##  Skip if it's unwanted.log, since it's already rotated.
+        if [ ${F} = ${UNWANTED_LOG} ]; then
+            continue
+        fi
+        ##  Skip if file doesn't exist.
+        BASE=$(basename ${F})
+        test -f ${BASE} || continue
 
-	##  Compress the file.
-	${LOG_COMPRESS} <${BASE} >${BASE}.0${Z} && rm -f ${BASE}
-	chmod 0440 ${BASE}.0${Z}
+        ##  Compress the file.
+        ${LOG_COMPRESS} <${BASE} >${BASE}.0${Z} && rm -f ${BASE}
+        chmod 0440 ${BASE}.0${Z}
 
-	##  Do rotation.
-	EXT=${LOGCYCLES}
-	rm -f ${BASE}.${LOGCYCLES}${Z}
-	while [ ${EXT} -gt 0 ] ; do
-	    NEXT=${EXT}
-	    EXT=`expr ${EXT} - 1`
-	    test -f ${BASE}.${EXT}${Z} \
-		&& rm -f ${BASE}.${NEXT}${Z} \
-		&& mv ${BASE}.${EXT}${Z} ${BASE}.${NEXT}${Z}
-	done
+        ##  Do rotation.
+        EXT=${LOGCYCLES}
+        rm -f ${BASE}.${LOGCYCLES}${Z}
+        while [ ${EXT} -gt 0 ]; do
+            NEXT=${EXT}
+            EXT=$(expr ${EXT} - 1)
+            test -f ${BASE}.${EXT}${Z} \
+                && rm -f ${BASE}.${NEXT}${Z} \
+                && mv ${BASE}.${EXT}${Z} ${BASE}.${NEXT}${Z}
+        done
     done
 
     ##  Remove lock.
diff --git a/scripts/writelog.in b/scripts/writelog.in
--- a/scripts/writelog.in
+++ b/scripts/writelog.in
@@ -3,14 +3,14 @@
 
 ##  Write a log file entry, by either mailing it or writing it safely.
 ##  Usage:
-##	writelog name text... <input
+##      writelog name text... <input
 ##  where
-##	name	is 'mail' to mail it, or filename to append to.
+##      name    is 'mail' to mail it, or filename to append to.
 
 MAXTRY=60
 
 ##  Parse arguments.
-if [ $# -lt 2 ] ; then
+if [ $# -lt 2 ]; then
     echo "usage: $0 'logfile|mail' message ..." 1>&2
     exit 1
 fi
@@ -30,7 +30,7 @@ Xmail)
 esac
 
 ##  We're sending to a file.
-LOCK=${LOCKS}/LOCK.`basename ${LOGFILE}`
+LOCK=${LOCKS}/LOCK.$(basename ${LOGFILE})
 
 ##  Remember our PID, in case while is a sub-shell.
 PID=$$
@@ -40,7 +40,7 @@ export LOCK MAXTRY PID LOGFILE ARTICLE MESSAGE TRY
 while [ ${TRY} -lt ${MAXTRY} ]; do
     shlock -p ${PID} -f ${LOCK} && break
     sleep 2
-    TRY=`expr ${TRY} + 1`
+    TRY=$(expr ${TRY} + 1)
 done
 
 ##  If we got the lock, update the file; otherwise, give up.
@@ -51,5 +51,5 @@ if [ ${TRY} -lt ${MAXTRY} ]; then
     rm -f ${LOCK}
 else
     ##  This goes to errlog, usually.
-    echo "$0: Cannot grab lock ${LOCK}, held by:" `cat ${LOCK}` 1>&2
+    echo "$0: Cannot grab lock ${LOCK}, held by:" $(cat ${LOCK}) 1>&2
 fi
