This set of changes all has to do with enabling support for getting ftp://ftp.isc.org/pub/usenet/CONFIG/active file for managing the active file.  Specifically:
  MANIFEST:  lists new file in samples: mod-active.in and simpleftp.in
  configure.in:  Look for ncftp or wget for fetching active file
  simpleftp.in:  Used if neither ncftp nor wget is found.
  innshellvars*: $GETFTP is ncftp, wget or simpleftp
  actsyncd.sh.in: Support either ftp or nntp retrieval of remote active file
  actsync.cfg.in: Use ftp://ftp.isc.org/pub/usenet/CONFIG/active by default
  mod-active.in: process actsync or checkgroups output efficiently, performing
	all newgroup/rmgroup/changegroup in one innd pause/edit/reload action.
  site/Makefile: install mod-active and simpleftp

diff --git a/backends/actsyncd.sh.in b/backends/actsyncd.sh.in
--- a/backends/actsyncd.sh.in
+++ b/backends/actsyncd.sh.in
@@ -26,30 +26,18 @@
 . @LIBDIR@/innshellvars
 
 # Our lock file
-LOCK=${LOCKS}/LOCK.actsyncd
+LOCK="${LOCKS}/LOCK.actsyncd"
 # where actsync is located
-ACTSYNC=${PATHBIN}/actsync
-# timeout for ctlinnd
-TIMEOUT=120
+ACTSYNC="${PATHBIN}/actsync"
 # exit value of actsync if unable to get an active file
 NOSYNC=127
-# where ctlinnd lives
-CTLINND="${PATHBIN}/ctlinnd"
-# by default we xexec instead of reloading
-XEXEC=
-export XEXEC
 
 # parse args
 #
 if [ $# -gt 1 ]; then
-    if [ X"-x" = X"$1" ]; then
-	XEXEC=true
-	shift
-    elif [ X"-r" = X"$1" ]; then
-	# backward compatibility
-	XEXEC=
-	shift
-    fi
+    case $1 in
+    -x|-r) shift ;;     # no longer relevant
+    esac
 fi
 case $# in
     1) cfg="$1"; DEBUG=; DEBUG_FMT=; ;;
@@ -65,25 +53,27 @@ fi
 
 # parse config_file
 #
-host="`sed -n -e 's/#.*//' -e 's/^host=[ 	]*//p' $cfg | tail -1`"
+host="`sed -n -e 's/^host=[ 	]*//p' $cfg | tail -1`"
 if [ -z "$host" ]; then
     echo "$0: no host specified in $cfg" 1>&2
     exit 3
 fi
-flags="`sed -n -e 's/#.*//' -e 's/^flags=[ 	]*//p' $cfg | tail -1`"
+flags="`sed -n -e 's/^flags=[ 	]*//p' $cfg | tail -1`"
 if [ -z "$flags" ]; then
     echo "$0: no flags specified in $cfg" 1>&2
     exit 4
 fi
-ign="`sed -n -e 's/#.*//' -e 's/^ignore_file=[ 	]*//p' $cfg | tail -1`"
+ign="`sed -n -e 's/^ignore_file=[ 	]*//p' $cfg | tail -1`"
 if [ -z "$ign" ]; then
     echo "$0: no ignore file specified in $cfg" 1>&2
     exit 5
 fi
-spool="`sed -n -e 's/#.*//' -e 's/^spool=[ 	]*//p' $cfg | tail -1`"
+ftp="`sed   -n -e 's/^ftppath=[ 	]*//p' $cfg | tail -1`"
+spool="`sed -n -e 's/^spool=[ 	]*//p' $cfg | tail -1`"
 if [ -z "$spool" ]; then
-    echo "$0: no spool directory specified in $cfg" 1>&2
-    exit 6
+    spool=$SPOOL
+    #echo "$0: no spool directory specified in $cfg" 1>&2
+    #exit 6
 fi
 if [ ! -s "$ign" ]; then
     echo "$0: ignore_file not found or empty: $ign" 1>&2
@@ -94,16 +84,21 @@ fi
 #
 flags="$flags -S $spool"
 
-# force -o a1 mode (overrides any -o argument in the command line)
+# force -o c mode (overrides any -o argument in the command line)
 #
 if [ -z "$DEBUG" ]; then
 
     # standard actsyncd output mode
-    flags="$flags -o a1"
+    flags="$flags -o c"
 
-# DEBUG processing, ig debug_level was given
+# DEBUG processing, if debug_level was given
 #
 else
+
+    if [ ! -z "$ftp" ]; then
+        echo "$0: cannot use DEBUG mode with ftp (yet)" >&2
+        exit 88;
+    fi
 
     # force -v level as needed
     flags="$flags -v $DEBUG"
@@ -127,20 +122,27 @@ fi
 
 # Lock out others
 #
-trap 'rm -f ${LOCK}; exit 1' 0 1 2 3 15
-shlock -p $$ -f ${LOCK} || {
-    echo "$0: Locked by `cat ${LOCK}`" 1>&2
+shlock -p $$ -f "${LOCK}" || {
+    echo "$0: Locked by `cat '${LOCK}'`" 1>&2
     exit 9
 }
 
 # setup
 #
-activenew="${PATHETC}/active.new.$$"
-out="${TMPDIR}/.sync.$$"
-trap "rm -f $activenew $out ${LOCK}; exit" 0 1 2 3 15
+workdir="${TMPDIR}/actsyncd"
+ctlinndcmds="cc_commands"
+out="sync.msg"
+cleanup="$SED -e 's/^/    /' < $out; rm -rf '$workdir' '$LOCK'"
+trap "eval $cleanup; exit 123" 1 2 3 15
 rm -f "$out"
 touch "$out"
 chmod 0644 "$out"
+
+set -e
+rm -rf "$workdir"
+mkdir "$workdir"
+cd "$workdir"
+set +e
 
 # try to sync 
 # 
@@ -150,132 +152,76 @@ chmod 0644 "$out"
 echo "=-= `date` for $host" >>$out 2>&1
 for loop in 1 2 3 4 5 6 7 8 9 10; do
 
-    # pause the server
-    #
-    echo "=-= `date` for $host pause innd" >>$out 2>&1
-    ${CTLINND} pause "actsyncd" >>$out
-    if [ $? -ne 0 ]; then
-	echo "FATAL: `date` for $host cannot pause innd" >>$out
-	sed -e 's/^/    /' < "$out"
-	exit 10
+    # get the active file to compare against
+    if [ -z "$ftp" ]; then
+       echo "getlist -h $host" >>$out
+       if getlist -h $host > active 2>>$out; then
+         :
+       else
+         status=$NOSYNC
+       fi
+    else
+       echo "$GETFTP ftp://$host/$ftp" >>$out
+       $GETFTP ftp://$host/$ftp >>$out 2>&1
+       status=$?
+       if [ "$status" -ne 0 ]; then
+         status=$NOSYNC
+       else
+         case "$ftp" in
+         # This isn't bulletproof.  $COMPRESS might be compress, which 
+         # does not understand gzip.
+         *.gz|*.Z) echo "$COMPRESS -d active" >>$out
+               if $COMPRESS -d active  >>$out 2>&1; then
+                 :
+               else
+                 status=1
+               fi ;;
+         esac
+       fi
     fi
 
-    # form the new active file
-    #
-    echo "rm -f $activenew" >>$out
-    rm -f "$activenew" >>$out 2>&1
-    echo "touch $activenew" >>$out
-    touch "$activenew" >>$out 2>&1
-    echo "chmod 0644 $activenew" >>$out
-    chmod 0644 "$activenew" >>$out 2>&1
-    echo "$ACTSYNC -i $ign $flags $host" >>$out
-    eval "$ACTSYNC -i $ign $flags $host >$activenew 2>>$out"
-    status=$?
     if [ "$status" -ne "$NOSYNC" ]; then
 
 	# detect bad status
 	#
 	if [ "$status" -ne 0 ]; then
 	    echo "FATAL: `date` for $host exit $status" >>$out
-	    ${CTLINND} go "actsyncd" >>$out
-	    sed -e 's/^/    /' < "$out"
+            eval $cleanup
 	    exit "$status"
 	fi
 
-	# detect empty output
-	#
-	if [ ! -s "$activenew" ]; then
-	    echo "FATAL: `date` for $host empty or missing $activenew" >>$out
-	    ${CTLINND} go "actsyncd" >>$out
-	    sed -e 's/^/    /' < "$out"
-	    exit 11
-	fi
+        echo "$ACTSYNC -i $ign $flags ./active" >>$out
+        eval "$ACTSYNC -i $ign $flags ./active >$ctlinndcmds 2>>$out"
 
-	# form active.times lines for new newsgroups
-	#
-	# determine seconds since the Epoch (1 Jan 1970 0:00:00 UTC)
-	EP_FMT='X%S + \( X%M \* 60 \) + \( X%H \* 3600 \) + \( X%j \* 86400 \) + \( \( X%y - 70 \) \* 31536000 \) + \( \( \( X%y - 73 \) / 4 \) \* 86400 \)'
-	NOW=`eval expr \`TZ=UTC date "+$EP_FMT" | sed -e 's/X00* /0 /' -e 's/X0*/0/g'\``
-	if [ -z "${NOW}" ]; then
-	    echo "FATAL: `date` for $host secs output is empty" >>$out
-	    ${CTLINND} go "actsyncd" >>$out
-	    sed -e 's/^/    /' < "$out"
-	    exit 12
-	fi
-	echo "=-= `date` for $host, forming active.times" >>$out
-	eval "$ACTSYNC -i $ign $flags -o c -v 0 -q 12 ${ACTIVE} $activenew 2>>$out" | \
-	    grep '^ctlinnd newgroup ' | \
-	    awk '{print $3, NOW, "actsyncd";}' NOW=$NOW - >> ${ACTIVETIMES}
+        if [ $? -ne 0 ]; then
+            echo "FATAL: `date` for $host actsync balked" >>$out
+            eval $cleanup
+            exit $?
+        fi
 
-	# move the active file into place
-	#
-	wc "${ACTIVE}.old" "${ACTIVE}" "$activenew" | sed -e 's/^  *//' >>$out
-	echo "rm -f ${ACTIVE}.old" >>$out
-	rm -f "${ACTIVE}.old" >>$out 2>&1
-	echo "ln ${ACTIVE} ${ACTIVE}.old" >>$out
-	ln "${ACTIVE}" "${ACTIVE}.old" >>$out 2>&1
-	echo "mv -f $activenew ${ACTIVE}" >>$out
-	mv -f "$activenew" "${ACTIVE}" >>$out 2>&1
+        if [ ! -s $ctlinndcmds ]; then
+            echo "No changes need to be made" >>$out
+        else
+            echo "=-= `date` for $host, updating active" >>$out
+            echo "mod-active $ctlinndcmds" >>$out
+            mod-active $ctlinndcmds >>$out 2>&1
 
-	# reload the new active or reexec the server if needed
-	#
-	if [ -z "$XEXEC" ]; then
-	    # reload the modified active file
-	    #
-	    echo "=-= `date` for $host, reload active" >>$out
-	    ${CTLINND} reload active actsyncd >>$out 2>&1
-	    if [ $? -ne 0 ]; then
-		echo "FATAL: `date` for $host cannot reload active" >>$out
-		sed -e 's/^/    /' < "$out"
-		exit 13
-	    fi
-
-	    # active file has been updated successfully, resume server
-	    #
-	    echo "=-= `date` for $host, go innd" >>$out
-	    ${CTLINND} go "actsyncd" >>$out
-	    if [ $? -ne 0 ]; then
-		echo "FATAL: `date` for $host cannot go innd" >>$out
-		sed -e 's/^/    /' < "$out"
-		exit 14
-	    fi
-	else
-	    # just re-exec the server and let the new server read new active
-	    #
-	    echo "=-= `date` for $host, xexec" >>$out
-	    ${CTLINND} xexec '' >>$out 2>&1
-	    if [ $? -ne 0 ]; then
-		echo "FATAL: `date` for $host cannot xexec, server dead" >>$out
-		sed -e 's/^/    /' < "$out"
-		exit 15
-	    fi
-	    # see if the server has reloaded
-	    #
-	    sleep 30
-	    ${CTLINND} mode >/dev/null 2>&1
-	    if [ $? -ne 0 ]; then
-		echo "FATAL: `date` for $host did not resume after xexec" >>$out
-		sed -e 's/^/    /' < "$out"
-		exit 16
-	    fi
-	fi
+            if [ $? -ne 0 ]; then
+                echo "FATAL: `date` for $host mod-active FAILED" >>$out
+                eval $cleanup
+        	exit 1
+            fi
+        fi
 
 	# normal exit - all done
 	#
 	echo "=-= `date` for $host, end" >>$out
-	sed -e 's/^/    /' < "$out"
-	exit "$status"
+        eval $cleanup
+	exit 0
     fi
 
-    # failed to form the active file, resume server
-    #
+    # failed to get the remote active file
     echo "=-= `date` for $host failed to connect/sync, retrying" >>$out
-    ${CTLINND} go "actsyncd" >>$out
-    if [ $? -ne 0 ]; then
-	echo "FATAL: `date` for $host cannot go innd" >>$out
-	sed -e 's/^/    /' < "$out"
-	exit 17
-    fi
 
     # wait 6 minutes
     #
@@ -285,5 +231,5 @@ done
 # give up
 #
 echo "FATAL: `date` for $host failed to connect/sync 10 times" >>$out 2>&1
-sed -e 's/^/    /' < "$out"
-exit "$status"
+eval $cleanup
+exit 1
