Unified Overview Implementation Mega-Patch
From: Katsuhiro Kondou <kondou@nec.co.jp>

With that patch, we can expire and rebuild history,
overview and index for storage api in reasonable
time.

diff --git a/samples/news.daily.in b/samples/news.daily.in
--- a/samples/news.daily.in
+++ b/samples/news.daily.in
@@ -5,6 +5,7 @@
 ##	expdir=xxx	Directory in which to build new history file
 ##	expirectl=xxx	Use xxx as expire.ctl file
 ##	flags=xxx	Pass xxx flags to expire
+##	lowmark		Create and use a lowmark file.
 ##	noexpire	Do not expire
 ##	noexplog	Do not log expire output
 ##	nologs		Do not scan logfiles
@@ -24,6 +25,8 @@ EXPLOG=${MOST_LOGS}/expire.log
 INNSTAT=${NEWSBIN}/innstat
 HOSTNAME=`hostname`
 DATE=`date`
+AZ=ABCDEFGHIJKLMNOPQRSTUVWXYZ
+az=abcdefghijklmnopqrstuvwxyz
 
 ##  If your expire does not pause or throttle innd, enable this next line:
 #MESSAGE="Expiration script $$"
@@ -47,10 +50,28 @@ DOSTAT=true
 EXPIRECTL=
 EXPDIR=
 EXPIREFLAGS="-v1"
+SAPI=`innconfval storageapi | tr ${AZ} ${az}`
+if [ X${SAPI} = X"true" ]; then
+    EXPIREOVER=expireindex
+    INDEXFILE=${MOST_LOGS}/expire.index.rm
+    EXPIREFLAGS="${EXPIREFLAGS} -c -e"
+else
+    EXPIREOVER=expireover
+fi
+HISTDIR="`dirname ${HISTORY}`"
+TOUT=600   # timeout value for ctlinnd commands
+if [ -z "${HISTDIR}" -o X"." = X"${HISTDIR}" -o ! -d "${HISTDIR}" ]; then
+    if [ -d "${NEWSLIB}/hist" ]; then
+	HISTDIR="${NEWSLIB}/hist"
+    else
+	HISTDIR="${NEWSLIB}"
+    fi
+fi
 EXPIREOVERFLAGS=
 PROGRAMS=
 REASON=
 RMFILE=
+LOWMARKFILE=
 SCANARG=
 
 ##  Parse JCL.
@@ -82,6 +103,9 @@ do
     Xflags=*)
 	EXPIREFLAGS=`expr "${I}" : 'flags=\(.*\)'`
 	;;
+    Xlowmark)
+	LOWMARKFILE=${MOST_LOGS}/expire.lowmark
+ 	;;
     Xnotdaily)
         DAILY=false
 	DOLOGS=false
@@ -97,7 +121,7 @@ do
 	;;
     Xnomail)
 	DOMAIL=false
-	MAIL=cat
+	MAIL="cut -c 1-1022 | ${SED} -e 's/^~/~~/'"
 	;;
     Xnonn)
 	# Ignore this.
@@ -123,20 +147,23 @@ do
 	;;
     esac
 done
+
 ##
-## Setup mail subject
+## Setup mail subject and command
 ##
 if ${DAILY} ; then
-   MAILSUBJ="${HOSTNAME} daily usenet report for ${DATE}"
+   MAILSUBJ="${HOSTNAME} Daily Usenet report for ${DATE}"
 else
    MAILSUBJ="${HOSTNAME} intermediate usenet report for ${DATE}"
 fi
-
-MAIL="${MAILCMD} -s \"FAILED: ${MAILSUBJ}\" ${NEWSMASTER}"
+MAIL="cut -c 1-1022 | ${SED} -e 's/^~/~~/' | \
+    ${MAILCMD} -s '$MAILSUBJ' ${NEWSMASTER}"
 
 ${DOEXPIRE} || {
     EXPDIR=
     RMFILE=
+    INDEXFILE=
+    LOWMARKFILE=
 }
 
 test -n "${EXPDIR}" && {
@@ -145,16 +172,24 @@ test -n "${EXPDIR}" && {
 }
 
 test -n "${RMFILE}" && {
-    EXPIREFLAGS="${EXPIREFLAGS} -z${RMFILE}"
-    EXPIREOVERFLAGS="${EXPIREOVERFLAGS} -z ${RMFILE}.$$"
+    if [ X${SAPI} = X"true" ]; then
+	EXPIREFLAGS="${EXPIREFLAGS} -u${INDEXFILE} -z${RMFILE}"
+	EXPIREOVERFLAGS="${EXPIREOVERFLAGS} -z ${INDEXFILE}"
+    else
+	EXPIREFLAGS="${EXPIREFLAGS} -z${RMFILE}"
+    fi
 }
+
+test -n "${LOWMARKFILE}" && {
+    EXPIREFLAGS="${EXPIREFLAGS} -Z${LOWMARKFILE}"
+}
+
 test -z "${EXPIREOVERFLAGS}" && EXPIREOVERFLAGS=-s
 
 if ${DOMAIL} ; then
     ##  Try to get a temporary file.
     TEMP=${TMPDIR}/doex$$
     test -f ${TEMP} && {
-        MAIL="${MAILCMD} -s \"${HOSTNAME}: Delayed USENET report\" ${NEWSMASTER}"
 	echo "Temporary file ${TEMP} exists" | eval ${MAIL}
 	exit 1
     }
@@ -195,12 +230,17 @@ if ${DOEXPIRE} ; then
     sleep 30
 
     ##  See if we're throttled for lack of space.
-    SERVERMODE=`ctlinnd mode 2>/dev/null | ${SED} 1q`
+    SERVERMODE=`ctlinnd -t $TOUT mode 2>/dev/null | ${SED} 1q`
     case "${SERVERMODE}" in
     'Server paused'*'[innwatch:'*)
 	## If paused, by innwatch, then turn pause into throttle
 	## as we're going to stay that way for a while now
-	ctlinnd -s throttle "`expr \"${SERVERMODE}\" : 'Server paused \(.*\)'`"
+	ctlinnd -t $TOUT -s throttle \
+	    "`expr \"${SERVERMODE}\" : 'Server paused \(.*\)'`" || {
+	    ( echo "$0: Cannot throttle while innwatch paused";
+	      ${INNSTAT} ) | eval ${MAIL}
+	    exit 1
+	}
     esac
     case "${SERVERMODE}" in
     *space*" -- throttling")
@@ -223,7 +263,7 @@ if ${DOEXPIRE} ; then
 
     ##  Throttle server if we need to.
     if [ -n "${MESSAGE}" ] ; then
-	ctlinnd -s -t120 throttle "${MESSAGE}" 2>&1 || {
+	ctlinnd -t $TOUT -s -t120 throttle "${MESSAGE}" 2>&1 || {
 	    ( echo "$0: Cannot throttle news"; ${INNSTAT} ) | eval ${MAIL}
 	    exit 1
 	}
@@ -241,11 +281,12 @@ if ${DOEXPIRE} ; then
     test -n "${EXPIRECTL}" && EXPIREFLAGS="${EXPIREFLAGS} ${EXPIRECTL}"
     if ${DOEXPLOG}; then
 	echo "expire begin `date`: (${EXPIREFLAGS})"		>>${EXPLOG}
-	( exec 2>&1 ; eval expire "${EXPIREFLAGS}" ) \
-	    | ${SED} -e 's/^/    /' >>${EXPLOG}
+	( cd ${HISTDIR}; exec 2>&1 ; eval expire "${EXPIREFLAGS}" ) \
+	    | ${SED} -e '/No such file or directory/d' \
+		     -e 's/^/    /' >>${EXPLOG}
 	echo "expire end `date`"				>>${EXPLOG}
     else
-	eval expire "${EXPIREFLAGS}"
+	eval expire "${EXPIREFLAGS}" 2>&1 | grep -v 'No such file or directory'
     fi
 
     ##  If built on another filesystem, move history files.
@@ -254,6 +295,7 @@ if ${DOEXPIRE} ; then
 	    ( echo "$0: No new history files"; ${INNSTAT} ) | eval ${MAIL}
 	    exit 1
 	fi
+	cp /dev/null ${HISTORY}
 	mv -f ${EXPDIR}/history.n ${HISTORY}
 	mv -f ${EXPDIR}/history.n.dir ${HISTORY}.dir
 	mv -f ${EXPDIR}/history.n.index ${HISTORY}.index
@@ -270,10 +312,13 @@ if ${DOEXPIRE} ; then
 
     ##  Restart the server if we need to.
     if ${THROTTLED} || test -n "${MESSAGE}" ; then
-	ctlinnd -s go "${MESSAGE}" 2>&1 || {
+	ctlinnd -t "$TOUT" -s go "${MESSAGE}" 2>&1 || {
 	    ( echo "$0: Cannot unthrottle news"; ${INNSTAT} ) | eval ${MAIL}
 	    exit 1
 	}
+    fi
+    if ${DOEXPLOG}; then
+	echo "	all done `date`" >>${EXPLOG}
     fi
 fi
 
@@ -307,15 +352,66 @@ rm ${LOCK}
 if ${DOEXPIRE} ; then
     test -n "${RMFILE}" -a -s "${RMFILE}" && {
 	mv ${RMFILE} ${RMFILE}.$$ && RMFILE=${RMFILE}.$$
+
+        test -n "${LOWMARKFILE}" && {
+	    echo "lowmarkrenumber begin `date`: (${LOWMARKFILE})"   >>${EXPLOG}
+	    ctlinnd -s -t`wc -l <${ACTIVE}` lowmark ${LOWMARKFILE} 2>&1
+	    echo "lowmarkrenumber end `date`"			    >>${EXPLOG}
+	    # expireover with lowmark has less performance than sorted list
+	    # ${DOEXPIREOVER} && {
+	    #   if ${DOEXPLOG}; then
+	    #       echo "	${EXPIREOVER} start `date`" >>${EXPLOG}
+	    #   fi
+	    #   eval ${EXPIREOVER} "${EXPIREOVERFLAGS}" 2>&1 | \
+	    #     grep -v 'No such file or directory'
+	    #   DOEXPIREOVER=false
+	    #   if ${DOEXPLOG}; then
+	    #       echo "	${EXPIREOVER} end `date`" >>${EXPLOG}
+	    #   fi
+	    # }
+	    rm -f ${MOST_LOGS}/expire.lastlowmark
+	    mv ${LOWMARKFILE} ${MOST_LOGS}/expire.lastlowmark
+	}
+
 	test -n "${TMPDIR}" && T="-T ${TMPDIR}"
 	sort -u -o ${RMFILE} ${RMFILE}
+	if [ X${SAPI} = X"true" ]; then
+	    sort -u -o ${INDEXFILE} ${INDEXFILE}
+	fi
 	${DOEXPIREOVER} && {
-	    eval expireover "${EXPIREOVERFLAGS}"
+	    if ${DOEXPLOG}; then
+		echo "	${EXPIREOVER} start `date`" >>${EXPLOG}
+	    fi
+	    eval ${EXPIREOVER} "${EXPIREOVERFLAGS}" 2>&1 | \
+	      grep -v 'No such file or directory'
 	    DOEXPIREOVER=false
+	    if ${DOEXPLOG}; then
+		echo "	${EXPIREOVER} end `date`" >>${EXPLOG}
+	    fi
+	    if [ X${SAPI} = X"true" ]; then
+		rm -f ${MOST_LOGS}/expire.lastindex
+		mv ${INDEXFILE} ${MOST_LOGS}/expire.lastindex
+	    fi
 	}
+	if ${DOEXPLOG}; then
+	    echo "	expirerm start `date`" >>${EXPLOG}
+	fi
 	expirerm ${RMFILE}
+	if ${DOEXPLOG}; then
+	    echo "	expirerm end `date`" >>${EXPLOG}
+	fi
     }
-    ${DOEXPIREOVER} && eval expireover "${EXPIREOVERFLAGS}"
+    # expire overview lines for files we just removed
+    if ${DOEXPIREOVER}; then
+	if ${DOEXPLOG}; then
+	    echo "	${EXPIREOVER} start `date`" >>${EXPLOG}
+	fi
+	eval ${EXPIREOVER} "${EXPIREOVERFLAGS}" 2>&1 | \
+	    grep -v 'No such file or directory'
+	if ${DOEXPLOG}; then
+	    echo "	${EXPIREOVER} end `date`" >>${EXPLOG}
+	fi
+    fi
 fi
 
 ##  Renumber the active file.
