scripts/Makefile: scripts/innshellvars.in: scripts/innshellvars.pl.in: scripts/rc.news.in: scripts/dbprocs.in: 	- From: Heath Kehoe <hakehoe@norand.com> 	- Makefile.global.in:  Removed LIBNEWS variable. 	- Makefiles:  Replaced LIBNEWS with LIBINN and (where necessary) 	  LIBSTORAGE.  Now LIBSTORAGE is only linked with programs that need it. 	- configure.in:  Added --with-berkeleydb option (for ovdb). 	- controlchan.in:  Fixed problem where control.ctl lines starting 	  with 'all' were not working.  The 'all' needs to be converted 	  to '.*' so the regexp would match.  Also made the sender 	  comparison case-insensitive. 	- inndf.c:  Move ReadInnConf() before OVopen() 	- makehistory.8, makehistory.c:  Added new option (-F) to make 	  it fork() to write overview data in a separate process 	- rc.news.in:  rc.news will now stop INN if given 'stop' as an 	  argument.  This is so all of the script code to start and stop 	  INN can be in one place. 	- cnfsstat.in:  Added option (-P) to make it write its PID into 	  a file.  This is to make it easy to automatically kill. 	- added a simple example SysV-style-init script 	- ov.c, buffindexed.c, tradindexed.c:  Consolidated redundant 	  code in buffindexed.c and tradindexed.c (from method_add) 	  into ov.c:OVadd().

diff --git a/scripts/rc.news.in b/scripts/rc.news.in
--- a/scripts/rc.news.in
+++ b/scripts/rc.news.in
@@ -5,6 +5,38 @@
 ##  News boot script.  Runs as "news" user.  Requires inndstart be
 ##  setuid root.  Run from rc.whatever as:
 ##     su news -c /path/to/rc.news >/dev/console
+##
+##  Or to stop INN:
+##     su news -c '/path/to/rc.news stop'
+
+case X"$1" in
+Xstop)
+    ${PATHBIN}/ctlinnd shutdown 'rc.news stop'
+
+    # Stop cnfsstat (if running)
+    if [ -f ${PATHRUN}/cnfsstat.pid ]; then
+	kill `cat ${PATHRUN}/cnfsstat.pid`
+	rm -f ${PATHRUN}/cnfsstat.pid
+    fi
+
+    # Stop innwatch (if running)
+    if [ -f $WATCHPID ]; then
+	kill `cat $WATCHPID`
+	rm -f $WATCHPID
+    fi
+
+    # give innd some time to exit
+    sleep 10
+
+    # Turn off ovdb support procs, and close the DB environment
+    if [ "$OVMETHOD" = "ovdb" -a -n "$DB_HOME" ]; then
+	${PATHBIN}/dbprocs stop
+    fi
+
+    exit 0
+;;
+esac
+
 
 AZ=ABCDEFGHIJKLMNOPQRSTUVWXYZ
 az=abcdefghijklmnopqrstuvwxyz
@@ -93,6 +125,15 @@ fi
 ( cd ${TEMPSOCKDIR} && rm -f ${TEMPSOCK} )
 rm -f ${NEWSCONTROL} ${NNTPCONNECT} ${SERVERPID}
 
+## In case the ovdb database was not properly shutdown, this will
+## fix it.  Must be done before starting innd.
+if [ "$OVMETHOD" = "ovdb" -a -n "$DB_HOME" ]; then
+    ovdb_recover || {
+	echo "Can't recover ov database (check news.err for OVDB messages)"
+	exit 1
+    }
+fi
+
 ##  Start the show.
 echo 'Starting innd.'
 eval ${WHAT} ${RFLAG} ${INNFLAGS}
@@ -105,8 +146,15 @@ ${DOINNWATCH} && {
 
 ${DOCNFSSTAT} && {
     echo "Scheduled start of cnfsstat."
-    ( sleep 60 ; ${PATHBIN}/cnfsstat -s -l ) &
+    ( sleep 60 ; ${PATHBIN}/cnfsstat -s -l -P ) &
 }
+
+## Stuff to support ovdb.  Must be started after innd has initialized
+## overview.
+if [ "$OVMETHOD" = "ovdb" -a -s "$DB_HOME" ]; then
+    echo "Scheduled start of dbprocs."
+    ( sleep 60 ; ${PATHBIN}/dbprocs start ) &
+fi
 
 RMFILE=${MOST_LOGS}/expire.rm
 for F in ${RMFILE} ${RMFILE}.*; do
@@ -120,3 +168,4 @@ for F in ${RMFILE} ${RMFILE}.*; do
 	${PATHBIN}/expirerm ${F}
     fi
 done &
+
