Rotate innfeed logs
Exploder and process channels are now properly reopened when "ctlinnd 
flushlogs" is used, which is in particular the command invoked by
scanlogs to rotate log files.
It solves the issue that caused the patch to be reverted by commit
[9450].

diff --git a/scripts/scanlogs.in b/scripts/scanlogs.in
--- a/scripts/scanlogs.in
+++ b/scripts/scanlogs.in
@@ -22,12 +22,21 @@ ACTIVEFILE=${ACTIVE}
 ##  Where these programs, if used, write their logs.
 ##  We also have to find innfeed's log file.
 CONTROLBATCH=${MOST_LOGS}/controlbatch.log
+INNFEEDCONF=${PATHETC}/innfeed.conf
+if [ -f "${INNFEEDCONF}" ]; then
+    INNFEEDLOG=`${AWK} '{gsub(/:|#/, " & ")} {if ($1 == "log-file" && $2 == ":") print $3}' ${INNFEEDCONF}`
+fi
+INNFEED=
+for F in "${INNFEEDLOG}" ; do
+    test -f "${MOST_LOGS}/${F}" && INNFEED="${INNFEED} ${MOST_LOGS}/${F}"
+done
+test -z "${INNFEED}" && test -f "${MOST_LOGS}/innfeed.log" && INNFEED="${MOST_LOGS}/innfeed.log"
 NNTPSEND=${MOST_LOGS}/nntpsend.log
 PERLNOCEM=${MOST_LOGS}/perl-nocem.log
 SENDIHAVE=${MOST_LOGS}/send-ihave.log
 SENDNNTP=${MOST_LOGS}/send-nntp.log
 SENDUUCP=${MOST_LOGS}/send-uucp.log
-LIVEFILES="${CONTROLBATCH} ${NNTPSEND} ${PERLNOCEM} ${SENDIHAVE} ${SENDNNTP} ${SENDUUCP}"
+LIVEFILES="${CONTROLBATCH} ${INNFEED} ${NNTPSEND} ${PERLNOCEM} ${SENDIHAVE} ${SENDNNTP} ${SENDUUCP}"
 
 ##  Where news.daily places expire output, unless noexplog was used.
 EXPLOG=${MOST_LOGS}/expire.log
@@ -102,6 +111,9 @@ if ${ROTATE} ; then
     ctlinnd -s logmode
     PAUSED=false
     ctlinnd -s pause "Flushing log and syslog files" 2>&1 && PAUSED=true
+
+    # First, flush log files to be sure everything has been recorded
+    # before rotating them.
     OUTPUT=`ctlinnd flushlogs 2>&1`
     if [ "$OUTPUT" != "Ok" -a "$OUTPUT" != "In debug mode" ]; then
 	echo "$OUTPUT"
@@ -147,6 +159,16 @@ if ${ROTATE} ; then
 
     ##  Tally control messages if we logged them.
     test -n "${CONTROL_DATA}" && cat ${CONTROL_DATA} | ${TALLY_CONTROL}
+
+    # Flush again log files so that freshly rotated new log files
+    # are properly taken into account.
+    OUTPUT=`ctlinnd flushlogs 2>&1`
+    if [ "$OUTPUT" != "Ok" -a "$OUTPUT" != "In debug mode" ]; then
+        echo "$OUTPUT"
+        echo 'Cannot flush logs.'
+        rm -f ${LOCK}
+        exit 1
+    fi
 
     ${PAUSED} && ctlinnd -s go "Flushing log and syslog files" 2>&1
 
