Fix the test suite (collateral issue after the migration to Lenny: not adding "\n" to the end of this line prevents any error to be raised... not even one triggered by "exit 1").

diff --git a/tests/nnrpd/auth-test b/tests/nnrpd/auth-test
--- a/tests/nnrpd/auth-test
+++ b/tests/nnrpd/auth-test
@@ -55,7 +55,7 @@ partial)
     ;;
 partial-error)
     printf 'User:tester'
-    printf 'This is an error' >&2
+    echo 'This is an error' >&2
     exit 1
     ;;
 esac
